# Generated by Django 5.1.5 on 2026-08-02 06:13

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('masters', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTrackingUnit',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('code', models.CharField(db_index=True, help_text='B-YYYY-NNNN／W-YYYY-NNNN', max_length=30, verbose_name='編號')),
                ('unit_type', models.CharField(choices=[('batch', '構件批次'), ('work_item', '土建工項')], max_length=12, verbose_name='類型')),
                ('name', models.CharField(help_text='如「第一期-1F鋼柱」', max_length=200, verbose_name='名稱')),
                ('stage_entered_at', models.DateTimeField(default=django.utils.timezone.now, help_text='停滯天數判定用', verbose_name='進入目前階段時間')),
                ('status', models.CharField(choices=[('ontrack', '正常'), ('atrisk', '注意'), ('delayed', '延誤')], default='ontrack', max_length=10, verbose_name='狀態')),
                ('qty_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='總數量')),
                ('qty_done', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='已完成數量')),
                ('unit_of_measure', models.CharField(blank=True, help_text='支／組／噸／片／件', max_length=10, verbose_name='單位')),
                ('total_weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text='鋼構論噸計價。也是「累計達 X%」與「分批按量請款」的計算基準。編輯權限限廠長／專案負責人／經營者', max_digits=12, null=True, verbose_name='總重量(kg)')),
                ('progress_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='完成百分比')),
                ('subcontract_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='分包契約金額')),
                ('work_mode', models.CharField(choices=[('self', '鐵正綱自行'), ('outsource', '外包協力廠')], default='self', max_length=12, verbose_name='作業方式')),
                ('outsource_in_date', models.DateField(blank=True, null=True, verbose_name='實際進廠日')),
                ('outsource_due_date', models.DateField(blank=True, null=True, verbose_name='預計出廠日')),
                ('outsource_out_date', models.DateField(blank=True, null=True, verbose_name='實際出廠日')),
                ('signoff_date', models.DateField(blank=True, db_index=True, help_text='業主／監造簽收日。登錄後才觸發請款評估', null=True, verbose_name='簽收日')),
                ('signoff_by_name', models.CharField(blank=True, help_text='業主方人員姓名（非系統使用者）', max_length=50, verbose_name='簽收人')),
                ('signoff_doc_no', models.CharField(blank=True, max_length=40, verbose_name='簽收單號')),
                ('plan_start', models.DateField(blank=True, null=True, verbose_name='預計開始')),
                ('plan_end', models.DateField(blank=True, null=True, verbose_name='預計完成')),
                ('actual_start', models.DateField(blank=True, null=True, verbose_name='實際開始')),
                ('actual_end', models.DateField(blank=True, null=True, verbose_name='實際完成')),
                ('rollback_count', models.SmallIntegerField(default=0, help_text='≥2 次自動升級為延誤', verbose_name='回退次數')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='備註')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('assignee', models.ForeignKey(blank=True, db_constraint=False, help_text='「我的工作」畫面的依據', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='指派給')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('current_stage', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.stage', verbose_name='目前階段')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('outsource_vendor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.vendor', verbose_name='協力廠')),
                ('phase', models.ForeignKey(blank=True, db_constraint=False, help_text='決定簽收時觸發哪一筆請款里程碑', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.projectphase', verbose_name='期別')),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.project', verbose_name='專案')),
                ('signoff_location', models.ForeignKey(blank=True, db_constraint=False, help_text='與里程碑的指定交貨地點比對，不符時警告但不阻擋', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.location', verbose_name='簽收地點')),
                ('subcontractor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.vendor', verbose_name='分包商')),
                ('template', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.stagetemplate', verbose_name='階段模板')),
                ('transport_vendor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.vendor', verbose_name='運輸廠商')),
            ],
            options={
                'verbose_name': 'historical 追蹤單元',
                'verbose_name_plural': 'historical 追蹤單元',
                'db_table': 'tracking_trackingunit_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TrackingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('code', models.CharField(help_text='B-YYYY-NNNN／W-YYYY-NNNN', max_length=30, unique=True, verbose_name='編號')),
                ('unit_type', models.CharField(choices=[('batch', '構件批次'), ('work_item', '土建工項')], max_length=12, verbose_name='類型')),
                ('name', models.CharField(help_text='如「第一期-1F鋼柱」', max_length=200, verbose_name='名稱')),
                ('stage_entered_at', models.DateTimeField(default=django.utils.timezone.now, help_text='停滯天數判定用', verbose_name='進入目前階段時間')),
                ('status', models.CharField(choices=[('ontrack', '正常'), ('atrisk', '注意'), ('delayed', '延誤')], default='ontrack', max_length=10, verbose_name='狀態')),
                ('qty_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='總數量')),
                ('qty_done', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='已完成數量')),
                ('unit_of_measure', models.CharField(blank=True, help_text='支／組／噸／片／件', max_length=10, verbose_name='單位')),
                ('total_weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text='鋼構論噸計價。也是「累計達 X%」與「分批按量請款」的計算基準。編輯權限限廠長／專案負責人／經營者', max_digits=12, null=True, verbose_name='總重量(kg)')),
                ('progress_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='完成百分比')),
                ('subcontract_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='分包契約金額')),
                ('work_mode', models.CharField(choices=[('self', '鐵正綱自行'), ('outsource', '外包協力廠')], default='self', max_length=12, verbose_name='作業方式')),
                ('outsource_in_date', models.DateField(blank=True, null=True, verbose_name='實際進廠日')),
                ('outsource_due_date', models.DateField(blank=True, null=True, verbose_name='預計出廠日')),
                ('outsource_out_date', models.DateField(blank=True, null=True, verbose_name='實際出廠日')),
                ('signoff_date', models.DateField(blank=True, db_index=True, help_text='業主／監造簽收日。登錄後才觸發請款評估', null=True, verbose_name='簽收日')),
                ('signoff_by_name', models.CharField(blank=True, help_text='業主方人員姓名（非系統使用者）', max_length=50, verbose_name='簽收人')),
                ('signoff_doc_no', models.CharField(blank=True, max_length=40, verbose_name='簽收單號')),
                ('plan_start', models.DateField(blank=True, null=True, verbose_name='預計開始')),
                ('plan_end', models.DateField(blank=True, null=True, verbose_name='預計完成')),
                ('actual_start', models.DateField(blank=True, null=True, verbose_name='實際開始')),
                ('actual_end', models.DateField(blank=True, null=True, verbose_name='實際完成')),
                ('rollback_count', models.SmallIntegerField(default=0, help_text='≥2 次自動升級為延誤', verbose_name='回退次數')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='備註')),
                ('assignee', models.ForeignKey(blank=True, help_text='「我的工作」畫面的依據', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_units', to=settings.AUTH_USER_MODEL, verbose_name='指派給')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_units', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('current_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_units', to='masters.stage', verbose_name='目前階段')),
                ('outsource_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outsourced_units', to='masters.vendor', verbose_name='協力廠')),
                ('phase', models.ForeignKey(blank=True, help_text='決定簽收時觸發哪一筆請款里程碑', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='projects.projectphase', verbose_name='期別')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='projects.project', verbose_name='專案')),
                ('signoff_location', models.ForeignKey(blank=True, help_text='與里程碑的指定交貨地點比對，不符時警告但不阻擋', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_units', to='inventory.location', verbose_name='簽收地點')),
                ('subcontractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcontracted_units', to='masters.vendor', verbose_name='分包商')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='masters.stagetemplate', verbose_name='階段模板')),
                ('transport_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transported_units', to='masters.vendor', verbose_name='運輸廠商')),
            ],
            options={
                'verbose_name': '追蹤單元',
                'verbose_name_plural': '追蹤單元',
                'db_table': 'tracking_trackingunit',
                'ordering': ['project', 'current_stage__seq', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProgressLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_before', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='原數量')),
                ('qty_after', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='新數量')),
                ('pct_before', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='原百分比')),
                ('pct_after', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='新百分比')),
                ('delta', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='增減量')),
                ('note', models.CharField(blank=True, help_text='數值調降時必填', max_length=500, verbose_name='備註')),
                ('reported_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='系統時間，不可由使用者指定（防補登造假）', verbose_name='回報時間')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_reports', to=settings.AUTH_USER_MODEL, verbose_name='回報者')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to='tracking.trackingunit', verbose_name='追蹤單元')),
            ],
            options={
                'verbose_name': '進度歷程',
                'verbose_name_plural': '進度歷程',
                'db_table': 'tracking_progresslog',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackingUnitStageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stage_name', models.CharField(blank=True, max_length=30, verbose_name='原階段名稱')),
                ('to_stage_name', models.CharField(max_length=30, verbose_name='新階段名稱')),
                ('direction', models.CharField(choices=[('create', '建立'), ('forward', '推進'), ('backward', '回退')], max_length=10, verbose_name='方向')),
                ('reason_category', models.CharField(blank=True, choices=[('qc_fail', '品檢不合格'), ('dimension_error', '尺寸錯誤'), ('material_issue', '材料問題'), ('workmanship', '施工缺失'), ('owner_change', '業主變更'), ('other', '其他')], help_text='回退時必填。P3 品質成本統計的來源', max_length=20, verbose_name='原因類別')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='備註')),
                ('moved_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='異動時間')),
                ('from_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='masters.stage', verbose_name='原階段')),
                ('moved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_moves', to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
                ('to_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.stage', verbose_name='新階段')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_logs', to='tracking.trackingunit', verbose_name='追蹤單元')),
            ],
            options={
                'verbose_name': '階段歷程',
                'verbose_name_plural': '階段歷程',
                'db_table': 'tracking_trackingunitstagelog',
                'ordering': ['-moved_at'],
            },
        ),
        migrations.AddIndex(
            model_name='trackingunit',
            index=models.Index(fields=['project', 'unit_type'], name='tracking_tr_project_ea5622_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingunit',
            index=models.Index(fields=['current_stage'], name='tracking_tr_current_175a78_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingunit',
            index=models.Index(fields=['status'], name='tracking_tr_status_8a42bd_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingunit',
            index=models.Index(fields=['assignee', 'status'], name='tracking_tr_assigne_008676_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingunit',
            index=models.Index(fields=['stage_entered_at'], name='tracking_tr_stage_e_d9ddfd_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingunit',
            index=models.Index(fields=['project', 'phase'], name='tracking_tr_project_f2dcdb_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingunit',
            index=models.Index(condition=models.Q(('outsource_out_date__isnull', True)), fields=['work_mode', 'outsource_due_date'], name='idx_unit_outsource_pending'),
        ),
        migrations.AddConstraint(
            model_name='trackingunit',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('unit_type', 'batch'), _negated=True), models.Q(('qty_total__isnull', False), models.Q(('unit_of_measure', ''), _negated=True)), _connector='OR'), name='ck_unit_batch_requires_qty'),
        ),
        migrations.AddConstraint(
            model_name='trackingunit',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('unit_type', 'work_item'), _negated=True), ('progress_pct__isnull', False), _connector='OR'), name='ck_unit_workitem_requires_pct'),
        ),
        migrations.AddConstraint(
            model_name='trackingunit',
            constraint=models.CheckConstraint(condition=models.Q(('qty_done__gte', 0)), name='ck_unit_qty_done_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='trackingunit',
            constraint=models.CheckConstraint(condition=models.Q(('qty_total__isnull', True), ('qty_done__lte', models.F('qty_total')), _connector='OR'), name='ck_unit_qty_done_lte_total'),
        ),
        migrations.AddConstraint(
            model_name='trackingunit',
            constraint=models.CheckConstraint(condition=models.Q(('qty_total__isnull', True), ('qty_total__gt', 0), _connector='OR'), name='ck_unit_qty_total_positive'),
        ),
        migrations.AddConstraint(
            model_name='trackingunit',
            constraint=models.CheckConstraint(condition=models.Q(('progress_pct__isnull', True), models.Q(('progress_pct__gte', 0), ('progress_pct__lte', 100)), _connector='OR'), name='ck_unit_pct_range'),
        ),
        migrations.AddConstraint(
            model_name='trackingunit',
            constraint=models.CheckConstraint(condition=models.Q(('outsource_out_date__isnull', True), ('outsource_in_date__isnull', True), ('outsource_out_date__gte', models.F('outsource_in_date')), _connector='OR'), name='ck_unit_outsource_dates'),
        ),
        migrations.AddIndex(
            model_name='progresslog',
            index=models.Index(fields=['unit', '-reported_at'], name='tracking_pr_unit_id_0af24c_idx'),
        ),
        migrations.AddIndex(
            model_name='progresslog',
            index=models.Index(fields=['reported_by', '-reported_at'], name='tracking_pr_reporte_70c2c3_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingunitstagelog',
            index=models.Index(fields=['unit', '-moved_at'], name='tracking_tr_unit_id_18c1c9_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingunitstagelog',
            index=models.Index(fields=['direction', 'moved_at'], name='tracking_tr_directi_8e8eac_idx'),
        ),
    ]
