# Generated by Django 5.1.5 on 2026-08-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingunitstagelog',
            name='pct_at_exit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='離開時完成百分比'),
        ),
        migrations.AddField(
            model_name='trackingunitstagelog',
            name='qty_at_exit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='離開時完成數量'),
        ),
    ]
