# Generated by Django 5.1.5 on 2026-08-14 12:34

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_flowstage_flowitem'),
        ('projects', '0002_historicalproject_estimate_amount_and_more'),
        ('tracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalFlowUnit',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('detail', models.TextField(blank=True, help_text='專案管理者寫給負責人的工作說明——要做什麼、注意什麼、交付什麼', verbose_name='詳細內容')),
                ('state', models.CharField(choices=[('todo', '未開始'), ('doing', '進行中'), ('done', '已完成'), ('na', '不適用')], default='todo', max_length=10, verbose_name='狀態')),
                ('plan_start', models.DateField(blank=True, null=True, verbose_name='預計開始')),
                ('plan_end', models.DateField(blank=True, help_text='甘特圖與金流預測靠它', null=True, verbose_name='預計完成')),
                ('actual_start', models.DateField(blank=True, null=True, verbose_name='實際開始')),
                ('actual_end', models.DateField(blank=True, null=True, verbose_name='實際完成')),
                ('qty_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='總數量')),
                ('qty_done', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='已完成數量')),
                ('unit_of_measure', models.CharField(blank=True, max_length=10, verbose_name='單位')),
                ('progress_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='完成百分比')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='備註')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('assignee', models.ForeignKey(blank=True, db_constraint=False, help_text='指派時對方會收到通知，在「我的任務」看到這件事', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='負責人')),
                ('flow_item', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.flowitem', verbose_name='流程工作項')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.project', verbose_name='專案')),
                ('subcontractor', models.ForeignKey(blank=True, db_constraint=False, help_text='這件事外包給誰。錢在「金流 → 應付」逐筆掛回本單元', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.vendor', verbose_name='分包商／協力廠')),
            ],
            options={
                'verbose_name': 'historical 流程單元',
                'verbose_name_plural': 'historical 流程單元',
                'db_table': 'tracking_flowunit_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='FlowUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('detail', models.TextField(blank=True, help_text='專案管理者寫給負責人的工作說明——要做什麼、注意什麼、交付什麼', verbose_name='詳細內容')),
                ('state', models.CharField(choices=[('todo', '未開始'), ('doing', '進行中'), ('done', '已完成'), ('na', '不適用')], default='todo', max_length=10, verbose_name='狀態')),
                ('plan_start', models.DateField(blank=True, null=True, verbose_name='預計開始')),
                ('plan_end', models.DateField(blank=True, help_text='甘特圖與金流預測靠它', null=True, verbose_name='預計完成')),
                ('actual_start', models.DateField(blank=True, null=True, verbose_name='實際開始')),
                ('actual_end', models.DateField(blank=True, null=True, verbose_name='實際完成')),
                ('qty_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='總數量')),
                ('qty_done', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='已完成數量')),
                ('unit_of_measure', models.CharField(blank=True, max_length=10, verbose_name='單位')),
                ('progress_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='完成百分比')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='備註')),
                ('assignee', models.ForeignKey(blank=True, help_text='指派時對方會收到通知，在「我的任務」看到這件事', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_flow_units', to=settings.AUTH_USER_MODEL, verbose_name='負責人')),
                ('flow_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='masters.flowitem', verbose_name='流程工作項')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_units', to='projects.project', verbose_name='專案')),
                ('subcontractor', models.ForeignKey(blank=True, help_text='這件事外包給誰。錢在「金流 → 應付」逐筆掛回本單元', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flow_units', to='masters.vendor', verbose_name='分包商／協力廠')),
            ],
            options={
                'verbose_name': '流程單元',
                'verbose_name_plural': '流程單元',
                'db_table': 'tracking_flowunit',
                'ordering': ['project', 'flow_item__seq'],
                'indexes': [models.Index(fields=['project', 'state'], name='tracking_fl_project_a142a0_idx'), models.Index(fields=['assignee', 'state'], name='tracking_fl_assigne_e37f8d_idx'), models.Index(fields=['state', 'plan_end'], name='tracking_fl_state_085343_idx')],
                'constraints': [models.UniqueConstraint(fields=('project', 'flow_item'), name='uniq_flowunit_project_item'), models.CheckConstraint(condition=models.Q(('qty_done__gte', 0)), name='ck_flowunit_qty_nonneg'), models.CheckConstraint(condition=models.Q(('qty_total__isnull', True), ('qty_total__gt', 0), _connector='OR'), name='ck_flowunit_qty_total_positive'), models.CheckConstraint(condition=models.Q(('progress_pct__isnull', True), models.Q(('progress_pct__gte', 0), ('progress_pct__lte', 100)), _connector='OR'), name='ck_flowunit_pct_range')],
            },
        ),
    ]
