# Generated by Django 5.1.5 on 2026-08-17 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_historicalflowunit_flowunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('name', models.CharField(help_text='要採購／製作的東西，如「鐵材」', max_length=100, verbose_name='內容物')),
                ('qty', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='數量')),
                ('unit_of_measure', models.CharField(blank=True, max_length=10, verbose_name='單位')),
                ('status', models.CharField(default='未開始', max_length=20, verbose_name='狀態')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tracking.flowunit', verbose_name='流程單元')),
            ],
            options={
                'verbose_name': '工作項目',
                'verbose_name_plural': '工作項目',
                'db_table': 'tracking_flowtask',
                'ordering': ['id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('qty__isnull', True), ('qty__gt', 0), _connector='OR'), name='ck_flowtask_qty_positive')],
            },
        ),
    ]
