# Generated by Django 5.1.5 on 2026-08-18 02:38
#
# D40：工作內容／產出物／完成條件下放到流程單元（目錄只是新案的預設值）。
# 既有單元用資料遷移從 flow_item 抄一份，看起來跟改版前一模一樣。

from django.db import migrations, models


def copy_spec_from_catalog(apps, schema_editor):
    FlowUnit = apps.get_model("tracking", "FlowUnit")
    for unit in FlowUnit.objects.select_related("flow_item").iterator():
        unit.description = unit.flow_item.description
        unit.deliverables = unit.flow_item.deliverables
        unit.done_criteria = unit.flow_item.done_criteria
        unit.save(update_fields=["description", "deliverables", "done_criteria"])


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_flowtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowunit',
            name='deliverables',
            field=models.TextField(blank=True, verbose_name='產出物'),
        ),
        migrations.AddField(
            model_name='flowunit',
            name='description',
            field=models.TextField(blank=True, verbose_name='工作內容'),
        ),
        migrations.AddField(
            model_name='flowunit',
            name='done_criteria',
            field=models.TextField(blank=True, verbose_name='完成條件'),
        ),
        migrations.AddField(
            model_name='historicalflowunit',
            name='deliverables',
            field=models.TextField(blank=True, verbose_name='產出物'),
        ),
        migrations.AddField(
            model_name='historicalflowunit',
            name='description',
            field=models.TextField(blank=True, verbose_name='工作內容'),
        ),
        migrations.AddField(
            model_name='historicalflowunit',
            name='done_criteria',
            field=models.TextField(blank=True, verbose_name='完成條件'),
        ),
        migrations.RunPython(copy_spec_from_catalog, migrations.RunPython.noop),
    ]
