# Generated by Django 5.1.5 on 2026-08-18 03:34
#
# D41：工作項目的狀態改成單元層級的選項清單＋新表「工作分配」。
# 既有單元的清單＝預設頭尾之間插入項目已經在用的狀態，下拉選單不會缺字。

import django.db.models.deletion
import main.apps.tracking.models.flow_unit
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def fold_existing_statuses(apps, schema_editor):
    FlowUnit = apps.get_model("tracking", "FlowUnit")
    for unit in FlowUnit.objects.filter(tasks__isnull=False).distinct():
        in_use = []
        for task in unit.tasks.order_by("id"):
            s = task.status
            if s and s not in in_use and s not in ("未開始", "已完成"):
                in_use.append(s)
        if in_use:
            unit.task_statuses = ["未開始", *in_use, "已完成"]
            unit.save(update_fields=["task_statuses"])


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_flowunit_deliverables_flowunit_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flowunit',
            name='task_statuses',
            field=models.JSONField(blank=True, default=main.apps.tracking.models.flow_unit.default_task_statuses, verbose_name='工作項目狀態選項'),
        ),
        migrations.AddField(
            model_name='historicalflowunit',
            name='task_statuses',
            field=models.JSONField(blank=True, default=main.apps.tracking.models.flow_unit.default_task_statuses, verbose_name='工作項目狀態選項'),
        ),
        migrations.CreateModel(
            name='FlowTaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('status', models.CharField(help_text='對應單元狀態選項裡的一項（頭尾「未開始／已完成」除外），如「切割中」', max_length=20, verbose_name='工段')),
                ('qty_assigned', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='分配數量')),
                ('qty_done', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='已完成數量')),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_assignments', to=settings.AUTH_USER_MODEL, verbose_name='負責員工')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tracking.flowtask', verbose_name='工作項目')),
            ],
            options={
                'verbose_name': '工作分配',
                'verbose_name_plural': '工作分配',
                'db_table': 'tracking_flowtaskassignment',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['assignee'], name='tracking_fl_assigne_74559c_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('qty_assigned__gt', 0)), name='ck_taskassign_qty_positive'), models.CheckConstraint(condition=models.Q(('qty_done__gte', 0), ('qty_done__lte', models.F('qty_assigned'))), name='ck_taskassign_done_range')],
            },
        ),
        migrations.RunPython(fold_existing_statuses, migrations.RunPython.noop),
    ]
