# Generated by Django 5.1.5 on 2026-08-18 06:46
#
# D45：狀態清單下放到工作項目（每個內容物的工序不同）。
# 既有項目從單元的 task_statuses 抄（去掉頭尾），分配資料不會變孤兒。

from django.db import migrations, models


def copy_unit_statuses(apps, schema_editor):
    FlowTask = apps.get_model("tracking", "FlowTask")
    for task in FlowTask.objects.select_related("unit").iterator():
        stages = [s for s in task.unit.task_statuses if s not in ("未開始", "已完成")]
        if stages:
            task.statuses = stages
            task.save(update_fields=["statuses"])


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_merge_detail_into_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowtask',
            name='statuses',
            field=models.JSONField(blank=True, default=list, verbose_name='狀態清單（工段）'),
        ),
        migrations.RunPython(copy_unit_statuses, migrations.RunPython.noop),
    ]
