# Generated by Django 5.1.5 on 2026-08-29 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_flowtemplate_alter_flowitem_code_alter_flowitem_seq_and_more'),
        ('tracking', '0007_flowtask_statuses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flowunit',
            options={'ordering': ['project', 'seq', 'id'], 'verbose_name': '流程單元', 'verbose_name_plural': '流程單元'},
        ),
        migrations.AddField(
            model_name='flowtaskassignment',
            name='note',
            field=models.CharField(blank=True, help_text='經理分配時的叮嚀（D49）——被分到的人在「我的任務」會特別看到這段話', max_length=500, verbose_name='注意事項'),
        ),
        migrations.AddField(
            model_name='flowunit',
            name='name',
            field=models.CharField(blank=True, help_text='自訂流程的名稱；目錄流程留空、顯示目錄名', max_length=50, verbose_name='自訂名稱'),
        ),
        migrations.AddField(
            model_name='flowunit',
            name='seq',
            field=models.IntegerField(blank=True, help_text='生成時從目錄抄（seq×10），之後可拖移重排；小的排前面', null=True, verbose_name='案內順序'),
        ),
        migrations.AddField(
            model_name='flowunit',
            name='stage',
            field=models.ForeignKey(blank=True, help_text='生成時從目錄抄；自訂流程由使用者選', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flow_units', to='masters.flowstage', verbose_name='大階段'),
        ),
        migrations.AddField(
            model_name='historicalflowunit',
            name='name',
            field=models.CharField(blank=True, help_text='自訂流程的名稱；目錄流程留空、顯示目錄名', max_length=50, verbose_name='自訂名稱'),
        ),
        migrations.AddField(
            model_name='historicalflowunit',
            name='seq',
            field=models.IntegerField(blank=True, help_text='生成時從目錄抄（seq×10），之後可拖移重排；小的排前面', null=True, verbose_name='案內順序'),
        ),
        migrations.AddField(
            model_name='historicalflowunit',
            name='stage',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='生成時從目錄抄；自訂流程由使用者選', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.flowstage', verbose_name='大階段'),
        ),
        migrations.AlterField(
            model_name='flowunit',
            name='flow_item',
            field=models.ForeignKey(blank=True, help_text='自訂流程（D49）沒有目錄來源，此欄為空', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='units', to='masters.flowitem', verbose_name='流程工作項'),
        ),
        migrations.AlterField(
            model_name='historicalflowunit',
            name='flow_item',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='自訂流程（D49）沒有目錄來源，此欄為空', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.flowitem', verbose_name='流程工作項'),
        ),
    ]
