# Generated by Django 5.1.5 on 2026-08-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0009_backfill_unit_seq_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowunit',
            name='code',
            field=models.CharField(blank=True, help_text='依案內順序編（D51）：3.4 拖到 3.3 前面就變 3.3。由 flow_service.renumber_codes 維護，不手填', max_length=10, verbose_name='顯示編號'),
        ),
        migrations.AddField(
            model_name='historicalflowunit',
            name='code',
            field=models.CharField(blank=True, help_text='依案內順序編（D51）：3.4 拖到 3.3 前面就變 3.3。由 flow_service.renumber_codes 維護，不手填', max_length=10, verbose_name='顯示編號'),
        ),
    ]
