# Generated by Django 5.1.5 on 2026-08-30 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_materialitem_worktype'),
        ('tracking', '0011_backfill_unit_codes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flowtaskassignment',
            name='completed_at',
            field=models.DateField(blank=True, help_text='完成量報滿分配量的那天，系統自動記', null=True, verbose_name='完成日'),
        ),
        migrations.AddField(
            model_name='flowtaskassignment',
            name='man_days_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='空＝系統依回報自動計（一人一天＝1 工，記在當天有回報的分配上、多件均分）；經理覺得不準可在此直接填總工數蓋過', max_digits=6, null=True, verbose_name='工數（補登修正）'),
        ),
        migrations.AddField(
            model_name='flowtaskassignment',
            name='started_at',
            field=models.DateField(blank=True, help_text='員工在「我的任務」按「開始」的那天；回報過就自動視為已開始', null=True, verbose_name='實際開始日'),
        ),
        migrations.AddField(
            model_name='flowtaskassignment',
            name='work_type',
            field=models.ForeignKey(blank=True, help_text='產能統計的分類。新分配必選；D52 之前的舊資料為空＝未分類', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='masters.worktype', verbose_name='工作類型'),
        ),
        migrations.CreateModel(
            name='AssignmentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='預設當天；補登時可回填', verbose_name='回報日')),
                ('qty_delta', models.DecimalField(decimal_places=2, help_text='這次回報「新增」的完成量（更正時可為負）', max_digits=12, verbose_name='本次回報量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='寫入時間')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='tracking.flowtaskassignment', verbose_name='工作分配')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_reports', to=settings.AUTH_USER_MODEL, verbose_name='回報者')),
            ],
            options={
                'verbose_name': '回報紀錄',
                'verbose_name_plural': '回報紀錄',
                'db_table': 'tracking_assignmentreport',
                'ordering': ['date', 'id'],
                'indexes': [models.Index(fields=['assignment', 'date'], name='tracking_as_assignm_c55987_idx'), models.Index(fields=['date'], name='tracking_as_date_c8992b_idx')],
            },
        ),
    ]
