# Generated by Django 5.1.5 on 2026-09-01 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AffairCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='名稱')),
                ('color', models.CharField(default='#64748b', help_text='日曆色塊用，#RRGGBB', max_length=7, verbose_name='顏色')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用中')),
            ],
            options={
                'verbose_name': '行政類別',
                'verbose_name_plural': '行政類別',
                'db_table': 'affairs_category',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AffairRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('title', models.CharField(max_length=100, verbose_name='標題')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
                ('freq', models.CharField(choices=[('weekly', '每週'), ('monthly', '每月'), ('yearly', '每年')], max_length=10, verbose_name='頻率')),
                ('weekdays', models.JSONField(blank=True, default=list, help_text='每週用：0=週一 … 6=週日，可多選', verbose_name='星期幾')),
                ('month_day', models.PositiveSmallIntegerField(blank=True, help_text='每月用：1–31，超過當月天數以月底計', null=True, verbose_name='每月幾日')),
                ('year_month', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='每年幾月')),
                ('year_day', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='每年幾日')),
                ('start_date', models.DateField(verbose_name='起始日')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='結束日')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用中')),
                ('materialized_until', models.DateField(blank=True, null=True, verbose_name='已展開至')),
                ('assignees', models.ManyToManyField(blank=True, related_name='affair_rules', to=settings.AUTH_USER_MODEL, verbose_name='指派給')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='affairs.affaircategory', verbose_name='類別')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
            ],
            options={
                'verbose_name': '行政例行規則',
                'verbose_name_plural': '行政例行規則',
                'db_table': 'affairs_rule',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AffairTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('title', models.CharField(max_length=100, verbose_name='標題')),
                ('date', models.DateField(db_index=True, verbose_name='日期')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
                ('is_done', models.BooleanField(default=False, verbose_name='已完成')),
                ('done_at', models.DateTimeField(blank=True, null=True, verbose_name='完成時間')),
                ('assignees', models.ManyToManyField(blank=True, related_name='affair_tasks', to=settings.AUTH_USER_MODEL, verbose_name='指派給')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='affairs.affaircategory', verbose_name='類別')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='完成者')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='affairs.affairrule', verbose_name='例行規則')),
            ],
            options={
                'verbose_name': '行政事項',
                'verbose_name_plural': '行政事項',
                'db_table': 'affairs_task',
                'ordering': ['date', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('rule__isnull', False)), fields=('rule', 'date'), name='uniq_affair_rule_date')],
            },
        ),
    ]
