# Generated by Django 5.1.5 on 2026-08-02 06:13

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='如 WH-A-3-2', max_length=30, unique=True, verbose_name='位置代號')),
                ('name', models.CharField(help_text='如「A倉3排2層」', max_length=80, verbose_name='位置名稱')),
                ('location_type', models.CharField(choices=[('warehouse', '倉庫'), ('rack', '儲位'), ('yard', '置料區'), ('site', '工地'), ('vendor', '外包廠'), ('vehicle', '車輛'), ('office', '辦公室'), ('scrap', '廢料區')], max_length=20, verbose_name='類型')),
                ('capacity_note', models.CharField(blank=True, max_length=100, verbose_name='容量備註')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用中')),
            ],
            options={
                'verbose_name': '位置',
                'verbose_name_plural': '位置',
                'db_table': 'inventory_location',
                'ordering': ['location_type', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('lot_no', models.CharField(max_length=40, unique=True, verbose_name='批號')),
                ('qty_on_hand', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='現有量')),
                ('qty_reserved', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='已預留量')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='單位成本')),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='帳面價值')),
                ('status', models.CharField(choices=[('quarantine', '待驗收'), ('available', '可用'), ('reserved', '已預留'), ('issued', '已領用'), ('hold', '品質凍結'), ('scrapped', '已報廢')], default='quarantine', max_length=20, verbose_name='狀態')),
                ('received_date', models.DateField(blank=True, null=True, verbose_name='入庫日')),
                ('last_move_date', models.DateField(blank=True, help_text='庫齡計算基準', null=True, verbose_name='最後異動日')),
                ('aging_status', models.CharField(choices=[('normal', '正常'), ('slow', '緩動'), ('stagnant', '滯銷'), ('dead', '呆滯'), ('scrap_candidate', '報廢候選')], default='normal', max_length=20, verbose_name='庫齡狀態')),
                ('source_po_no', models.CharField(blank=True, max_length=30, verbose_name='來源採購單')),
                ('mill_cert_no', models.CharField(blank=True, max_length=50, verbose_name='材質證明編號')),
                ('heat_no', models.CharField(blank=True, help_text='鋼材追溯用', max_length=30, verbose_name='爐號')),
                ('is_remnant', models.BooleanField(default=False, help_text='切割後剩下的料頭', verbose_name='餘料')),
                ('actual_length_mm', models.DecimalField(blank=True, decimal_places=2, help_text='餘料的實際剩餘尺寸，「找料」查詢用', max_digits=10, null=True, verbose_name='實際長度(mm)')),
                ('actual_width_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='實際寬度(mm)')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='備註')),
            ],
            options={
                'verbose_name': '批號庫存',
                'verbose_name_plural': '批號庫存',
                'db_table': 'inventory_lot',
                'ordering': ['item', 'lot_no'],
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_type', models.CharField(choices=[('receipt', '入庫'), ('issue', '領用'), ('return', '退料'), ('transfer', '移轉'), ('adjust', '盤盈虧'), ('scrap', '報廢'), ('split', '切割分批')], max_length=20, verbose_name='異動類型')),
                ('qty', models.DecimalField(decimal_places=2, help_text='正負皆可', max_digits=12, verbose_name='異動量')),
                ('qty_before', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='異動前結存')),
                ('qty_after', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='異動後結存')),
                ('ref_doc_type', models.CharField(blank=True, max_length=20, verbose_name='來源單據類型')),
                ('ref_doc_no', models.CharField(blank=True, max_length=30, verbose_name='來源單號')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='單位成本')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='金額')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='異動時間')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='備註')),
            ],
            options={
                'verbose_name': '庫存異動',
                'verbose_name_plural': '庫存異動',
                'db_table': 'inventory_stocktransaction',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalLot',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('lot_no', models.CharField(db_index=True, max_length=40, verbose_name='批號')),
                ('qty_on_hand', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='現有量')),
                ('qty_reserved', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='已預留量')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='單位成本')),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='帳面價值')),
                ('status', models.CharField(choices=[('quarantine', '待驗收'), ('available', '可用'), ('reserved', '已預留'), ('issued', '已領用'), ('hold', '品質凍結'), ('scrapped', '已報廢')], default='quarantine', max_length=20, verbose_name='狀態')),
                ('received_date', models.DateField(blank=True, null=True, verbose_name='入庫日')),
                ('last_move_date', models.DateField(blank=True, help_text='庫齡計算基準', null=True, verbose_name='最後異動日')),
                ('aging_status', models.CharField(choices=[('normal', '正常'), ('slow', '緩動'), ('stagnant', '滯銷'), ('dead', '呆滯'), ('scrap_candidate', '報廢候選')], default='normal', max_length=20, verbose_name='庫齡狀態')),
                ('source_po_no', models.CharField(blank=True, max_length=30, verbose_name='來源採購單')),
                ('mill_cert_no', models.CharField(blank=True, max_length=50, verbose_name='材質證明編號')),
                ('heat_no', models.CharField(blank=True, help_text='鋼材追溯用', max_length=30, verbose_name='爐號')),
                ('is_remnant', models.BooleanField(default=False, help_text='切割後剩下的料頭', verbose_name='餘料')),
                ('actual_length_mm', models.DecimalField(blank=True, decimal_places=2, help_text='餘料的實際剩餘尺寸，「找料」查詢用', max_digits=10, null=True, verbose_name='實際長度(mm)')),
                ('actual_width_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='實際寬度(mm)')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='備註')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 批號庫存',
                'verbose_name_plural': 'historical 批號庫存',
                'db_table': 'inventory_lot_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
