# Generated by Django 5.1.5 on 2026-08-02 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('masters', '0001_initial'),
        ('projects', '0001_initial'),
        ('tracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallot',
            name='item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.item', verbose_name='物品'),
        ),
        migrations.AddField(
            model_name='historicallot',
            name='reserved_for_project',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.project', verbose_name='預留給專案'),
        ),
        migrations.AddField(
            model_name='location',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='inventory.location', verbose_name='上層位置'),
        ),
        migrations.AddField(
            model_name='location',
            name='project',
            field=models.ForeignKey(blank=True, help_text='類型為「工地」時必填，讓「料已進場」成為可查詢的事實', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_locations', to='projects.project', verbose_name='關聯專案'),
        ),
        migrations.AddField(
            model_name='location',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='類型為「外包廠」時必填，讓送外包的料仍在帳上', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_locations', to='masters.vendor', verbose_name='關聯廠商'),
        ),
        migrations.AddField(
            model_name='historicallot',
            name='location',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.location', verbose_name='目前位置'),
        ),
        migrations.AddField(
            model_name='lot',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='masters.item', verbose_name='物品'),
        ),
        migrations.AddField(
            model_name='lot',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='inventory.location', verbose_name='目前位置'),
        ),
        migrations.AddField(
            model_name='lot',
            name='parent_lot',
            field=models.ForeignKey(blank=True, help_text='餘料必填，可追溯回原始材質證明', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remnants', to='inventory.lot', verbose_name='來源批號'),
        ),
        migrations.AddField(
            model_name='lot',
            name='reserved_for_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_lots', to='projects.project', verbose_name='預留給專案'),
        ),
        migrations.AddField(
            model_name='historicallot',
            name='parent_lot',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='餘料必填，可追溯回原始材質證明', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.lot', verbose_name='來源批號'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='from_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='txn_from', to='inventory.location', verbose_name='來源位置'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='inventory.lot', verbose_name='批號'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_txns', to=settings.AUTH_USER_MODEL, verbose_name='操作者'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_txns', to='projects.project', verbose_name='領用給專案'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='to_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='txn_to', to='inventory.location', verbose_name='目的位置'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='tracking_unit',
            field=models.ForeignKey(blank=True, help_text='材料成本自動歸集的關鍵', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_txns', to='tracking.trackingunit', verbose_name='領用給追蹤單元'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['location_type'], name='inventory_l_locatio_88dd59_idx'),
        ),
        migrations.AddIndex(
            model_name='lot',
            index=models.Index(fields=['item', 'status'], name='inventory_l_item_id_3ad089_idx'),
        ),
        migrations.AddIndex(
            model_name='lot',
            index=models.Index(fields=['location'], name='inventory_l_locatio_71fd52_idx'),
        ),
        migrations.AddIndex(
            model_name='lot',
            index=models.Index(fields=['reserved_for_project'], name='inventory_l_reserve_599af9_idx'),
        ),
        migrations.AddIndex(
            model_name='lot',
            index=models.Index(fields=['aging_status', 'last_move_date'], name='inventory_l_aging_s_41fe5a_idx'),
        ),
        migrations.AddIndex(
            model_name='lot',
            index=models.Index(condition=models.Q(('is_remnant', True)), fields=['is_remnant', 'actual_length_mm'], name='idx_lot_remnant_search'),
        ),
        migrations.AddConstraint(
            model_name='lot',
            constraint=models.CheckConstraint(condition=models.Q(('qty_on_hand__gte', 0)), name='ck_lot_qty_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='lot',
            constraint=models.CheckConstraint(condition=models.Q(('qty_reserved__gte', 0), ('qty_reserved__lte', models.F('qty_on_hand'))), name='ck_lot_reserved_lte_onhand'),
        ),
        migrations.AddConstraint(
            model_name='lot',
            constraint=models.CheckConstraint(condition=models.Q(('is_remnant', False), ('parent_lot__isnull', False), _connector='OR'), name='ck_lot_remnant_needs_parent'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['lot', '-occurred_at'], name='inventory_s_lot_id_3116d4_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['project', 'occurred_at'], name='inventory_s_project_3ad895_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['tracking_unit'], name='inventory_s_trackin_4b6e20_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['txn_type', 'occurred_at'], name='inventory_s_txn_typ_d07d62_idx'),
        ),
    ]
