# Generated by Django 5.1.5 on 2026-08-02 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='parent_lot',
            field=models.ForeignKey(blank=True, help_text='餘料必填，可追溯回原始材質證明', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='remnants', to='inventory.lot', verbose_name='來源批號'),
        ),
    ]
