# Generated by Django 5.1.5 on 2026-08-02 06:13

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='產線代號')),
                ('name', models.CharField(help_text='如「雷射切割線 (HSG TLS)」', max_length=50, verbose_name='產線名稱')),
                ('status', models.CharField(choices=[('run', '運轉中'), ('changeover', '換線中'), ('repair', '維修'), ('idle', '閒置')], default='idle', max_length=12, verbose_name='狀態')),
                ('current_work', models.CharField(blank=True, help_text='P1 為純文字，P3 改為關聯工單', max_length=100, verbose_name='當前工單')),
                ('utilization', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='P1 人工填寫，P3 由報工資料自動計算 OEE', max_digits=5, verbose_name='稼動率(%)')),
                ('today_output', models.CharField(blank=True, max_length=50, verbose_name='今日產出')),
                ('sort_order', models.SmallIntegerField(default=0, verbose_name='顯示順序')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用中')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_lines', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '產線',
                'verbose_name_plural': '產線',
                'db_table': 'production_productionline',
                'ordering': ['sort_order', 'code'],
                'constraints': [models.CheckConstraint(condition=models.Q(('utilization__gte', 0), ('utilization__lte', 100)), name='ck_line_utilization_range')],
            },
        ),
    ]
