# Generated by Django 5.1.5 on 2026-09-08 12:47

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('date', models.DateField(unique=True, verbose_name='日期')),
                ('name', models.CharField(max_length=50, verbose_name='名稱')),
            ],
            options={
                'verbose_name': '國定假日',
                'verbose_name_plural': '國定假日',
                'db_table': 'payroll_holiday',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('level', models.PositiveSmallIntegerField(unique=True, verbose_name='級數')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='月投保薪資')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用中')),
            ],
            options={
                'verbose_name': '投保薪資分級',
                'verbose_name_plural': '投保薪資分級',
                'db_table': 'payroll_insurance_grade',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='PayrollPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('name', models.CharField(default='現行法規', max_length=50, verbose_name='名稱')),
                ('effective_from', models.DateField(blank=True, help_text='僅供辨識，例如 2026-01-01 基本工資調整生效日', null=True, verbose_name='適用起日')),
                ('min_hourly_wage', models.DecimalField(decimal_places=2, default=Decimal('196'), help_text='115 年（2026）起為 196 元／小時', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='最低時薪')),
                ('normal_hours_per_day', models.DecimalField(decimal_places=2, default=Decimal('8'), help_text='勞基法 §30：每日不得超過 8 小時', max_digits=4, verbose_name='每日正常工時')),
                ('default_daily_ot_hours', models.DecimalField(decimal_places=2, default=Decimal('0.5'), help_text='產生薪資單時自動帶入的每日加班時數，之後可逐人調整', max_digits=4, verbose_name='每日固定加班時數')),
                ('ot_weekday_1_rate', models.DecimalField(decimal_places=4, default=Decimal('1.34'), help_text='§24：延長工時 2 小時內，加給 1/3 以上', max_digits=5, verbose_name='平日加班前段倍率')),
                ('ot_weekday_1_hours', models.DecimalField(decimal_places=2, default=Decimal('2'), max_digits=4, verbose_name='平日加班前段時數')),
                ('ot_weekday_2_rate', models.DecimalField(decimal_places=4, default=Decimal('1.67'), help_text='§24：再延長 2 小時內，加給 2/3 以上', max_digits=5, verbose_name='平日加班後段倍率')),
                ('ot_restday_1_rate', models.DecimalField(decimal_places=4, default=Decimal('1.34'), max_digits=5, verbose_name='休息日前 2 小時倍率')),
                ('ot_restday_1_hours', models.DecimalField(decimal_places=2, default=Decimal('2'), max_digits=4, verbose_name='休息日前段時數')),
                ('ot_restday_2_rate', models.DecimalField(decimal_places=4, default=Decimal('1.67'), max_digits=5, verbose_name='休息日第 3–8 小時倍率')),
                ('ot_restday_2_hours', models.DecimalField(decimal_places=2, default=Decimal('6'), max_digits=4, verbose_name='休息日中段時數')),
                ('ot_restday_3_rate', models.DecimalField(decimal_places=4, default=Decimal('2.67'), max_digits=5, verbose_name='休息日超過 8 小時倍率')),
                ('holiday_rate', models.DecimalField(decimal_places=4, default=Decimal('2'), help_text='§39 加倍發給：出勤即再給一日工資（做 1 給 8）', max_digits=5, verbose_name='國定假日出勤倍率')),
                ('labor_insurance_rate', models.DecimalField(decimal_places=3, default=Decimal('12.5'), help_text='普通事故 11.5% ＋ 就業保險 1%', max_digits=6, verbose_name='勞保費率(%)')),
                ('labor_insurance_employee_share', models.DecimalField(decimal_places=3, default=Decimal('20'), help_text='勞工 20%／雇主 70%／政府 10%', max_digits=6, verbose_name='勞保勞工負擔(%)')),
                ('health_insurance_rate', models.DecimalField(decimal_places=3, default=Decimal('5.17'), max_digits=6, verbose_name='健保費率(%)')),
                ('health_insurance_employee_share', models.DecimalField(decimal_places=3, default=Decimal('30'), help_text='被保險人 30%／投保單位 60%／政府 10%', max_digits=6, verbose_name='健保本人負擔(%)')),
                ('health_max_dependents', models.PositiveSmallIntegerField(default=3, help_text='眷屬超過 3 口者以 3 口計', verbose_name='健保眷屬計費上限')),
                ('pension_employer_rate', models.DecimalField(decimal_places=3, default=Decimal('6'), max_digits=6, verbose_name='勞退雇主提繳(%)')),
                ('welfare_fund_rate', models.DecimalField(decimal_places=3, default=Decimal('1'), help_text='公司規定，按應發總額（未扣除前）計算', max_digits=6, verbose_name='員工福利金(%)')),
                ('daily_ot_hours_cap', models.DecimalField(decimal_places=2, default=Decimal('4'), help_text='§32：延長工時連同正常工時，一日不得超過 12 小時', max_digits=4, verbose_name='每日加班上限')),
                ('monthly_ot_hours_cap', models.DecimalField(decimal_places=2, default=Decimal('46'), help_text='§32：延長工時一個月不得超過 46 小時', max_digits=6, verbose_name='每月加班上限')),
            ],
            options={
                'verbose_name': '薪資法規參數',
                'verbose_name_plural': '薪資法規參數',
                'db_table': 'payroll_policy',
            },
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('year', models.PositiveSmallIntegerField(verbose_name='年')),
                ('month', models.PositiveSmallIntegerField(verbose_name='月')),
                ('workdays', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='系統以當月平日扣掉國定假日帶出預設值，可自行調整', max_digits=5, verbose_name='應上班天數')),
                ('normal_hours_per_day', models.DecimalField(decimal_places=2, default=Decimal('8'), max_digits=4, verbose_name='每日正常工時')),
                ('daily_ot_hours', models.DecimalField(decimal_places=2, default=Decimal('0.5'), help_text='產生薪資單時自動帶入；某個月不加班就填 0', max_digits=4, verbose_name='每日固定加班時數')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('confirmed', '已確認'), ('paid', '已發放')], default='draft', max_length=10, verbose_name='狀態')),
                ('policy_snapshot', models.JSONField(blank=True, default=dict, verbose_name='法規參數快照')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='確認時間')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='確認者')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
            ],
            options={
                'verbose_name': '薪資期間',
                'verbose_name_plural': '薪資期間',
                'db_table': 'payroll_period',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('work_days', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='上班天數')),
                ('normal_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='不含加班。預設＝上班天數 × 每日正常工時', max_digits=8, verbose_name='正常工時')),
                ('ot_weekday_1_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='平日加班前段時數')),
                ('ot_weekday_2_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='平日加班後段時數')),
                ('ot_restday_1_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='休息日前段時數')),
                ('ot_restday_2_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='休息日中段時數')),
                ('ot_restday_3_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='休息日超時時數')),
                ('holiday_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='國定假日出勤時數')),
                ('unpaid_leave_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='無薪假時數')),
                ('late_minutes', models.PositiveIntegerField(default=0, verbose_name='遲到分鐘')),
                ('early_leave_minutes', models.PositiveIntegerField(default=0, verbose_name='早退分鐘')),
                ('hourly_wage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='時薪（本月覆寫）')),
                ('insured_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='投保薪資（本月覆寫）')),
                ('dependents', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='健保眷屬口數（本月覆寫）')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
                ('gross', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='應發總額')),
                ('deduction', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='應扣總額')),
                ('net', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='實發金額')),
                ('employer_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='勞退提繳等公司出的錢，不從薪水扣', max_digits=14, verbose_name='雇主另負擔')),
                ('detail', models.JSONField(blank=True, default=list, verbose_name='計算明細')),
                ('warnings', models.JSONField(blank=True, default=list, verbose_name='提醒')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='payroll.payrollperiod', verbose_name='薪資期間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_records', to=settings.AUTH_USER_MODEL, verbose_name='員工')),
            ],
            options={
                'verbose_name': '薪資單',
                'verbose_name_plural': '薪資單',
                'db_table': 'payroll_record',
                'ordering': ['user__employee_no', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='PayrollLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('kind', models.CharField(choices=[('earning', '加項'), ('deduction', '扣項')], max_length=10, verbose_name='類型')),
                ('label', models.CharField(max_length=50, verbose_name='項目')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='金額')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='說明')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payroll.payrollrecord', verbose_name='薪資單')),
            ],
            options={
                'verbose_name': '薪資加扣項',
                'verbose_name_plural': '薪資加扣項',
                'db_table': 'payroll_line',
                'ordering': ['kind', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SalaryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('hourly_wage', models.DecimalField(blank=True, decimal_places=2, help_text='留空＝跟著法規參數的最低時薪走', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='時薪')),
                ('insured_salary', models.DecimalField(decimal_places=2, default=Decimal('29500'), help_text='勞健保用的申報級距，不是實發金額', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='投保薪資')),
                ('dependents', models.PositiveSmallIntegerField(default=0, help_text='跟著本人一起投保的家屬人數；超過上限以上限計', verbose_name='健保眷屬口數')),
                ('voluntary_pension_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='0–6%，員工自己選擇要不要多存', max_digits=5, verbose_name='勞退自願提繳(%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='納入薪資計算')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_profile', to=settings.AUTH_USER_MODEL, verbose_name='員工')),
            ],
            options={
                'verbose_name': '員工薪資設定',
                'verbose_name_plural': '員工薪資設定',
                'db_table': 'payroll_salary_profile',
                'ordering': ['user__employee_no', 'user__username'],
            },
        ),
        migrations.AddConstraint(
            model_name='payrollperiod',
            constraint=models.UniqueConstraint(fields=('year', 'month'), name='uniq_payroll_period'),
        ),
        migrations.AddConstraint(
            model_name='payrollrecord',
            constraint=models.UniqueConstraint(fields=('period', 'user'), name='uniq_payroll_record'),
        ),
    ]
