# Generated by Django 5.1.5 on 2026-09-09 12:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_seed_reference_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollpolicy',
            name='health_employer_head_factor',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.56'), help_text='本人 1 ＋ 全國平均眷口數 0.56（2024 起）。與員工實際眷屬數無關', max_digits=5, verbose_name='健保雇主計費人數'),
        ),
        migrations.AddField(
            model_name='payrollpolicy',
            name='health_insurance_employer_share',
            field=models.DecimalField(decimal_places=3, default=Decimal('60'), help_text='被保險人 30%／投保單位 60%／政府 10%', max_digits=6, verbose_name='健保投保單位負擔(%)'),
        ),
        migrations.AddField(
            model_name='payrollpolicy',
            name='labor_insurance_employer_share',
            field=models.DecimalField(decimal_places=3, default=Decimal('70'), help_text='公司出的部分。不從薪水扣，但要算進人事成本', max_digits=6, verbose_name='勞保雇主負擔(%)'),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='charge_health_insurance',
            field=models.BooleanField(default=True, help_text='健保不按日拆。月中離職者當月由下一個投保單位負擔，這裡取消勾選', verbose_name='本月計收健保'),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='insured_days',
            field=models.PositiveSmallIntegerField(default=30, help_text='到職當月＝30−到職日+1；離職當月＝離職日；整月＝30', verbose_name='勞保勞退計費天數'),
        ),
        migrations.AddField(
            model_name='salaryprofile',
            name='hire_date',
            field=models.DateField(blank=True, help_text='留空＝到職已久。到職當月的工時與保費會按實際在職日數算', null=True, verbose_name='到職日'),
        ),
        migrations.AddField(
            model_name='salaryprofile',
            name='resign_date',
            field=models.DateField(blank=True, help_text='留空＝仍在職。填了之後該月之後就不再產生薪資單', null=True, verbose_name='離職日'),
        ),
    ]
