# Generated by Django 5.1.5 on 2026-09-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_drop_superuser_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='is_workday',
            field=models.BooleanField(default=False, help_text='補班日打勾：本來是週末但要上班，會算進應上班天數', verbose_name='這天要上班'),
        ),
    ]
