# Generated by Django 5.1.5 on 2026-09-10 04:35

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_holiday_makeup_workday'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollpolicy',
            name='monthly_wage_divisor',
            field=models.DecimalField(decimal_places=2, default=Decimal('240'), help_text='平日每小時工資額 ＝ 月薪 ÷ 這個數。法定為 240（30 天 × 8 小時）', max_digits=6, verbose_name='月薪換算時薪的除數'),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='monthly_salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='月薪制才有用。調薪當月填這裡，不必回頭改員工設定', max_digits=12, null=True, verbose_name='月薪（本月覆寫）'),
        ),
        migrations.AddField(
            model_name='salaryprofile',
            name='monthly_salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='月薪制才要填。是「總額」還是「實領」由計薪方式決定', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='月薪'),
        ),
        migrations.AddField(
            model_name='salaryprofile',
            name='pay_type',
            field=models.CharField(choices=[('hourly', '時薪制'), ('monthly_gross', '月薪制（薪資總額）'), ('monthly_net', '月薪制（實際領取）')], default='hourly', help_text='時薪制看工時；月薪制填一個固定金額，工時只影響加班與請假', max_length=15, verbose_name='計薪方式'),
        ),
    ]
