# Generated by Django 5.1.5 on 2026-08-13 10:46

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='客戶代號')),
                ('name', models.CharField(max_length=100, verbose_name='客戶名稱')),
                ('tax_id', models.CharField(blank=True, max_length=8, verbose_name='統一編號')),
                ('contact_name', models.CharField(blank=True, max_length=50, verbose_name='聯絡人')),
                ('contact_phone', models.CharField(blank=True, max_length=30, verbose_name='聯絡電話')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='地址')),
                ('payment_term_type', models.CharField(choices=[('month_end', '月結'), ('from_invoice', '請款日起算'), ('from_acceptance', '驗收後起算')], default='month_end', max_length=20, verbose_name='付款條件')),
                ('payment_term_days', models.SmallIntegerField(default=60, help_text='常見 30／60／90。月結是「請款當月月底再加這些天」，不是從請款日起算', verbose_name='帳期天數')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用中')),
            ],
            options={
                'verbose_name': '客戶',
                'verbose_name_plural': '客戶',
                'db_table': 'masters_customer',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCustomer',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('code', models.CharField(db_index=True, max_length=20, verbose_name='客戶代號')),
                ('name', models.CharField(max_length=100, verbose_name='客戶名稱')),
                ('tax_id', models.CharField(blank=True, max_length=8, verbose_name='統一編號')),
                ('contact_name', models.CharField(blank=True, max_length=50, verbose_name='聯絡人')),
                ('contact_phone', models.CharField(blank=True, max_length=30, verbose_name='聯絡電話')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='地址')),
                ('payment_term_type', models.CharField(choices=[('month_end', '月結'), ('from_invoice', '請款日起算'), ('from_acceptance', '驗收後起算')], default='month_end', max_length=20, verbose_name='付款條件')),
                ('payment_term_days', models.SmallIntegerField(default=60, help_text='常見 30／60／90。月結是「請款當月月底再加這些天」，不是從請款日起算', verbose_name='帳期天數')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用中')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 客戶',
                'verbose_name_plural': 'historical 客戶',
                'db_table': 'masters_customer_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalVendor',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('code', models.CharField(db_index=True, max_length=20, verbose_name='廠商代號')),
                ('name', models.CharField(max_length=100, verbose_name='廠商名稱')),
                ('tax_id', models.CharField(blank=True, max_length=8, verbose_name='統一編號')),
                ('vendor_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('supplier', '供應商'), ('subcontractor', '分包商'), ('outsource', '外包加工'), ('transport', '運輸行')], max_length=20), default=list, help_text='可多選。同一家廠商可同時是供應商與外包加工廠', size=None, verbose_name='廠商類型')),
                ('contact_name', models.CharField(blank=True, max_length=50, verbose_name='聯絡人')),
                ('contact_phone', models.CharField(blank=True, max_length=30, verbose_name='聯絡電話')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='地址')),
                ('payment_terms', models.CharField(blank=True, max_length=100, verbose_name='付款條件')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用中')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 廠商',
                'verbose_name_plural': 'historical 廠商',
                'db_table': 'masters_vendor_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='StageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='模板代號')),
                ('name', models.CharField(max_length=50, verbose_name='模板名稱')),
                ('applies_to', models.CharField(choices=[('project_main', '專案主線'), ('steel_batch', '鋼構構件批次'), ('civil_work_item', '土建工項')], max_length=20, verbose_name='適用類型')),
                ('is_default', models.BooleanField(default=False, verbose_name='預設模板')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用中')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
            ],
            options={
                'verbose_name': '階段模板',
                'verbose_name_plural': '階段模板',
                'db_table': 'masters_stagetemplate',
                'ordering': ['applies_to', 'code'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('applies_to',), name='uniq_default_template_per_type')],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='廠商代號')),
                ('name', models.CharField(max_length=100, verbose_name='廠商名稱')),
                ('tax_id', models.CharField(blank=True, max_length=8, verbose_name='統一編號')),
                ('vendor_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('supplier', '供應商'), ('subcontractor', '分包商'), ('outsource', '外包加工'), ('transport', '運輸行')], max_length=20), default=list, help_text='可多選。同一家廠商可同時是供應商與外包加工廠', size=None, verbose_name='廠商類型')),
                ('contact_name', models.CharField(blank=True, max_length=50, verbose_name='聯絡人')),
                ('contact_phone', models.CharField(blank=True, max_length=30, verbose_name='聯絡電話')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='地址')),
                ('payment_terms', models.CharField(blank=True, max_length=100, verbose_name='付款條件')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用中')),
            ],
            options={
                'verbose_name': '廠商',
                'verbose_name_plural': '廠商',
                'db_table': 'masters_vendor',
                'ordering': ['code'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['vendor_types'], name='idx_vendor_types_gin')],
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.SmallIntegerField(help_text='1 起算', verbose_name='順序')),
                ('code', models.CharField(max_length=30, verbose_name='階段代號')),
                ('name', models.CharField(max_length=30, verbose_name='階段名稱')),
                ('color', models.CharField(default='#64748b', help_text='#RRGGBB', max_length=7, verbose_name='顏色')),
                ('stall_days', models.SmallIntegerField(blank=True, help_text='停留超過此天數列入「需要關注」。留空表示不檢查', null=True, verbose_name='停滯天數門檻')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用中')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='masters.stagetemplate', verbose_name='所屬模板')),
            ],
            options={
                'verbose_name': '階段',
                'verbose_name_plural': '階段',
                'db_table': 'masters_stage',
                'ordering': ['template', 'seq'],
                'constraints': [models.UniqueConstraint(fields=('template', 'seq'), name='uniq_stage_template_seq'), models.UniqueConstraint(fields=('template', 'code'), name='uniq_stage_template_code'), models.CheckConstraint(condition=models.Q(('seq__gte', 1)), name='ck_stage_seq_positive')],
            },
        ),
    ]
