# Generated by Django 5.1.5 on 2026-08-14 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.SmallIntegerField(help_text='1 起算', unique=True, verbose_name='順序')),
                ('code', models.CharField(help_text='s1..s5', max_length=10, unique=True, verbose_name='代號')),
                ('name', models.CharField(max_length=30, verbose_name='名稱')),
                ('gate', models.CharField(blank=True, help_text='跨過這個階段時必須存在的產出物，如「報價依據圖定版」', max_length=100, verbose_name='出口門檻')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用中')),
            ],
            options={
                'verbose_name': '流程大階段',
                'verbose_name_plural': '流程大階段',
                'db_table': 'masters_flowstage',
                'ordering': ['seq'],
            },
        ),
        migrations.CreateModel(
            name='FlowItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.SmallIntegerField(help_text='11,12,…,54，跨階段全域排序', unique=True, verbose_name='全域順序')),
                ('code', models.CharField(help_text='如 3.2', max_length=10, unique=True, verbose_name='代號')),
                ('name', models.CharField(max_length=50, verbose_name='名稱')),
                ('description', models.TextField(blank=True, verbose_name='工作內容')),
                ('deliverables', models.TextField(blank=True, help_text='一行一項，附件上傳的檢核參考', verbose_name='產出物')),
                ('done_criteria', models.CharField(blank=True, max_length=200, verbose_name='完成條件')),
                ('is_gate', models.BooleanField(default=False, help_text='如 3.3 業主圖面簽認——未過不得下料加工', verbose_name='硬門檻')),
                ('batch_stage_seq', models.SmallIntegerField(blank=True, help_text='階段 4 專用：構件批次走過此站序（含）即算進本流程的完成數。填了此欄且專案有批次時，進度由批次自動彙總，不手填', null=True, verbose_name='批次彙總門檻站序')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用中')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='masters.flowstage', verbose_name='大階段')),
            ],
            options={
                'verbose_name': '流程工作項',
                'verbose_name_plural': '流程工作項',
                'db_table': 'masters_flowitem',
                'ordering': ['seq'],
                'constraints': [models.CheckConstraint(condition=models.Q(('seq__gte', 1)), name='ck_flowitem_seq_positive')],
            },
        ),
    ]
