# Generated by Django 5.1.5 on 2026-08-29 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_flowstage_flowitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='名稱')),
                ('is_default', models.BooleanField(default=False, help_text='建案表單預先選中的那一套；全系統只有一套是預設', verbose_name='預設模板')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用中')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '流程模板',
                'verbose_name_plural': '流程模板',
                'db_table': 'masters_flowtemplate',
                'ordering': ['-is_default', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='flowitem',
            name='code',
            field=models.CharField(help_text='如 3.2（模板內唯一）', max_length=10, verbose_name='代號'),
        ),
        migrations.AlterField(
            model_name='flowitem',
            name='seq',
            field=models.SmallIntegerField(help_text='11,12,…,54，跨階段排序（模板內唯一）', verbose_name='模板內順序'),
        ),
        migrations.AddField(
            model_name='flowitem',
            name='template',
            field=models.ForeignKey(blank=True, help_text='D49 之前的舊資料由資料遷移補上預設模板', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='masters.flowtemplate', verbose_name='流程模板'),
        ),
        migrations.AddConstraint(
            model_name='flowitem',
            constraint=models.UniqueConstraint(fields=('template', 'seq'), name='uniq_flowitem_template_seq'),
        ),
        migrations.AddConstraint(
            model_name='flowitem',
            constraint=models.UniqueConstraint(fields=('template', 'code'), name='uniq_flowitem_template_code'),
        ),
    ]
