# Generated by Django 5.1.5 on 2026-08-02 06:13

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('asset_no', models.CharField(help_text='如 TL-0031', max_length=30, unique=True, verbose_name='財產編號')),
                ('serial_no', models.CharField(blank=True, max_length=60, verbose_name='製造商序號')),
                ('brand', models.CharField(blank=True, max_length=50, verbose_name='廠牌')),
                ('model', models.CharField(blank=True, max_length=50, verbose_name='型號')),
                ('asset_status', models.CharField(choices=[('idle', '閒置可用'), ('in_use', '使用中'), ('lent', '借出'), ('maintenance', '維修中'), ('calibration', '校驗中'), ('scrapped', '報廢'), ('lost', '遺失')], default='idle', max_length=20, verbose_name='狀態')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='購置日')),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='購置成本')),
                ('depreciation_years', models.SmallIntegerField(blank=True, null=True, verbose_name='折舊年限')),
                ('book_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='帳面價值')),
                ('last_maintenance_date', models.DateField(blank=True, null=True, verbose_name='上次保養日')),
                ('next_maintenance_date', models.DateField(blank=True, null=True, verbose_name='下次保養日')),
                ('calibration_due_date', models.DateField(blank=True, help_text='扭力扳手、量具、吊帶、吊具等需定期校驗的器具', null=True, verbose_name='校驗到期日')),
                ('photo', models.CharField(blank=True, max_length=300, verbose_name='照片路徑')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用中')),
            ],
            options={
                'verbose_name': '個體資產',
                'verbose_name_plural': '個體資產',
                'db_table': 'assets_assetunit',
                'ordering': ['asset_no'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAssetUnit',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('asset_no', models.CharField(db_index=True, help_text='如 TL-0031', max_length=30, verbose_name='財產編號')),
                ('serial_no', models.CharField(blank=True, max_length=60, verbose_name='製造商序號')),
                ('brand', models.CharField(blank=True, max_length=50, verbose_name='廠牌')),
                ('model', models.CharField(blank=True, max_length=50, verbose_name='型號')),
                ('asset_status', models.CharField(choices=[('idle', '閒置可用'), ('in_use', '使用中'), ('lent', '借出'), ('maintenance', '維修中'), ('calibration', '校驗中'), ('scrapped', '報廢'), ('lost', '遺失')], default='idle', max_length=20, verbose_name='狀態')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='購置日')),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='購置成本')),
                ('depreciation_years', models.SmallIntegerField(blank=True, null=True, verbose_name='折舊年限')),
                ('book_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='帳面價值')),
                ('last_maintenance_date', models.DateField(blank=True, null=True, verbose_name='上次保養日')),
                ('next_maintenance_date', models.DateField(blank=True, null=True, verbose_name='下次保養日')),
                ('calibration_due_date', models.DateField(blank=True, help_text='扭力扳手、量具、吊帶、吊具等需定期校驗的器具', null=True, verbose_name='校驗到期日')),
                ('photo', models.CharField(blank=True, max_length=300, verbose_name='照片路徑')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用中')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical 個體資產',
                'verbose_name_plural': 'historical 個體資產',
                'db_table': 'assets_assetunit_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='AssetMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('assign', '派用'), ('return', '歸還'), ('transfer', '移轉'), ('lend', '借出'), ('maintenance_in', '送修'), ('maintenance_out', '修畢'), ('calibrate', '校驗'), ('scrap', '報廢'), ('lost', '遺失')], max_length=20, verbose_name='異動類型')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='異動時間')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='備註')),
                ('from_holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_handed_out', to=settings.AUTH_USER_MODEL, verbose_name='原持有人')),
            ],
            options={
                'verbose_name': '資產異動',
                'verbose_name_plural': '資產異動',
                'db_table': 'assets_assetmovement',
                'ordering': ['-occurred_at'],
            },
        ),
    ]
