# Generated by Django 5.1.5 on 2026-08-02 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('inventory', '0001_initial'),
        ('masters', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmovement',
            name='from_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_moved_from', to='inventory.location', verbose_name='原位置'),
        ),
        migrations.AddField(
            model_name='assetmovement',
            name='from_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_moved_from', to='projects.project', verbose_name='原專案'),
        ),
        migrations.AddField(
            model_name='assetmovement',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_movements', to=settings.AUTH_USER_MODEL, verbose_name='操作者'),
        ),
        migrations.AddField(
            model_name='assetmovement',
            name='to_holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_received', to=settings.AUTH_USER_MODEL, verbose_name='新持有人'),
        ),
        migrations.AddField(
            model_name='assetmovement',
            name='to_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_moved_to', to='inventory.location', verbose_name='新位置'),
        ),
        migrations.AddField(
            model_name='assetmovement',
            name='to_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_moved_to', to='projects.project', verbose_name='新專案'),
        ),
        migrations.AddField(
            model_name='assetunit',
            name='current_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='projects.project', verbose_name='目前用於專案'),
        ),
        migrations.AddField(
            model_name='assetunit',
            name='holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='held_assets', to=settings.AUTH_USER_MODEL, verbose_name='目前持有人'),
        ),
        migrations.AddField(
            model_name='assetunit',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_units', to='masters.item', verbose_name='物品'),
        ),
        migrations.AddField(
            model_name='assetunit',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='inventory.location', verbose_name='目前位置'),
        ),
        migrations.AddField(
            model_name='assetmovement',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='assets.assetunit', verbose_name='資產'),
        ),
        migrations.AddField(
            model_name='historicalassetunit',
            name='current_project',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.project', verbose_name='目前用於專案'),
        ),
        migrations.AddField(
            model_name='historicalassetunit',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalassetunit',
            name='holder',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='目前持有人'),
        ),
        migrations.AddField(
            model_name='historicalassetunit',
            name='item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.item', verbose_name='物品'),
        ),
        migrations.AddField(
            model_name='historicalassetunit',
            name='location',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.location', verbose_name='目前位置'),
        ),
        migrations.AddIndex(
            model_name='assetunit',
            index=models.Index(fields=['asset_status'], name='assets_asse_asset_s_c48ef6_idx'),
        ),
        migrations.AddIndex(
            model_name='assetunit',
            index=models.Index(fields=['current_project'], name='assets_asse_current_d44d55_idx'),
        ),
        migrations.AddIndex(
            model_name='assetunit',
            index=models.Index(fields=['holder'], name='assets_asse_holder__ce7f40_idx'),
        ),
        migrations.AddIndex(
            model_name='assetunit',
            index=models.Index(fields=['location'], name='assets_asse_locatio_ff8cad_idx'),
        ),
        migrations.AddIndex(
            model_name='assetunit',
            index=models.Index(fields=['next_maintenance_date'], name='assets_asse_next_ma_0a3fd0_idx'),
        ),
        migrations.AddIndex(
            model_name='assetunit',
            index=models.Index(fields=['calibration_due_date'], name='assets_asse_calibra_cb2d64_idx'),
        ),
        migrations.AddIndex(
            model_name='assetmovement',
            index=models.Index(fields=['asset', '-occurred_at'], name='assets_asse_asset_i_4c45d8_idx'),
        ),
    ]
