# Generated by Django 5.1.5 on 2026-08-13 10:46

import simple_history.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('seq', models.SmallIntegerField(verbose_name='順序')),
                ('label', models.CharField(help_text='如「第一期（簽約）」', max_length=100, verbose_name='名稱')),
                ('condition', models.CharField(blank=True, help_text='合約原文，如「構件全數運抵工地並經業主簽收」。提醒自己何時可以請', max_length=200, verbose_name='合約條件')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='比例(%)')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='系統計算＝有效合約額×比例。變更單核准時，尚未請款的列會重算', max_digits=14, verbose_name='金額')),
                ('state', models.CharField(choices=[('pending', '未到'), ('claimable', '可請款'), ('invoiced', '已請款'), ('received', '已收款')], default='pending', max_length=12, verbose_name='狀態')),
                ('expected_date', models.DateField(blank=True, help_text='現金流預估靠它。填大概的月份即可，之後隨時可改', null=True, verbose_name='預計請款日')),
                ('claimable_at', models.DateTimeField(blank=True, help_text='「可請款放了 N 天沒開單」的提醒基準', null=True, verbose_name='轉可請款時間')),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='請款日')),
                ('invoice_no', models.CharField(blank=True, max_length=30, verbose_name='請款單號')),
                ('due_date', models.DateField(blank=True, help_text='請款日＋客戶帳期，開單時自動帶入，可覆寫。現金流的收入側靠它落格', null=True, verbose_name='預計收款日')),
                ('receive_date', models.DateField(blank=True, null=True, verbose_name='收款日')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='備註')),
            ],
            options={
                'verbose_name': '應收款',
                'verbose_name_plural': '應收款',
                'db_table': 'billing_billingmilestone',
                'ordering': ['project', 'seq'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalBillingMilestone',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('seq', models.SmallIntegerField(verbose_name='順序')),
                ('label', models.CharField(help_text='如「第一期（簽約）」', max_length=100, verbose_name='名稱')),
                ('condition', models.CharField(blank=True, help_text='合約原文，如「構件全數運抵工地並經業主簽收」。提醒自己何時可以請', max_length=200, verbose_name='合約條件')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='比例(%)')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='系統計算＝有效合約額×比例。變更單核准時，尚未請款的列會重算', max_digits=14, verbose_name='金額')),
                ('state', models.CharField(choices=[('pending', '未到'), ('claimable', '可請款'), ('invoiced', '已請款'), ('received', '已收款')], default='pending', max_length=12, verbose_name='狀態')),
                ('expected_date', models.DateField(blank=True, help_text='現金流預估靠它。填大概的月份即可，之後隨時可改', null=True, verbose_name='預計請款日')),
                ('claimable_at', models.DateTimeField(blank=True, help_text='「可請款放了 N 天沒開單」的提醒基準', null=True, verbose_name='轉可請款時間')),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='請款日')),
                ('invoice_no', models.CharField(blank=True, max_length=30, verbose_name='請款單號')),
                ('due_date', models.DateField(blank=True, help_text='請款日＋客戶帳期，開單時自動帶入，可覆寫。現金流的收入側靠它落格', null=True, verbose_name='預計收款日')),
                ('receive_date', models.DateField(blank=True, null=True, verbose_name='收款日')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='備註')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical 應收款',
                'verbose_name_plural': 'historical 應收款',
                'db_table': 'billing_milestone_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MilestoneLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_state', models.CharField(blank=True, max_length=12, verbose_name='原狀態')),
                ('to_state', models.CharField(max_length=12, verbose_name='新狀態')),
                ('reason', models.CharField(blank=True, help_text='往回轉時必填', max_length=500, verbose_name='原因')),
                ('amount_snapshot', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='金額快照')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='時間')),
            ],
            options={
                'verbose_name': '應收款歷程',
                'verbose_name_plural': '應收款歷程',
                'db_table': 'billing_milestonelog',
                'ordering': ['-changed_at'],
            },
        ),
    ]
