# Generated by Django 5.1.5 on 2026-08-02 06:13

import simple_history.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.SmallIntegerField(verbose_name='序號')),
                ('amount', models.DecimalField(decimal_places=2, help_text='單位：元。分批請款時＝里程碑金額×(該批噸數÷該期總噸數)', max_digits=14, verbose_name='金額')),
                ('source', models.CharField(choices=[('auto_signoff', '簽收自動產生'), ('manual', '人工建立')], max_length=20, verbose_name='來源')),
                ('state', models.CharField(choices=[('claimable', '可請款'), ('invoiced', '已請款'), ('received', '已收款')], default='claimable', max_length=12, verbose_name='狀態')),
                ('claimable_at', models.DateTimeField(auto_now_add=True, verbose_name='可請款時間')),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='請款日')),
                ('invoice_no', models.CharField(blank=True, max_length=30, verbose_name='請款單號')),
                ('receive_date', models.DateField(blank=True, null=True, verbose_name='收款日')),
                ('weight_kg_snapshot', models.DecimalField(blank=True, decimal_places=2, help_text='產生當時該批的重量，供日後對帳', max_digits=12, null=True, verbose_name='噸數快照')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='備註')),
            ],
            options={
                'verbose_name': '請款事件',
                'verbose_name_plural': '請款事件',
                'db_table': 'billing_billingclaim',
                'ordering': ['milestone', 'seq'],
            },
        ),
        migrations.CreateModel(
            name='BillingClaimLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_state', models.CharField(blank=True, max_length=12, verbose_name='原狀態')),
                ('to_state', models.CharField(max_length=12, verbose_name='新狀態')),
                ('reason', models.CharField(blank=True, help_text='往回轉時必填', max_length=500, verbose_name='原因')),
                ('is_auto', models.BooleanField(default=False, verbose_name='系統自動')),
                ('amount_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='金額快照')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='異動時間')),
            ],
            options={
                'verbose_name': '請款狀態歷程',
                'verbose_name_plural': '請款狀態歷程',
                'db_table': 'billing_billingclaimlog',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='BillingMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('seq', models.SmallIntegerField(verbose_name='順序')),
                ('label', models.CharField(help_text='如「第一期請款」', max_length=100, verbose_name='名稱')),
                ('trigger_desc', models.CharField(blank=True, help_text='合約原文，如「第一期構件全數運抵工地並經業主簽收」', max_length=200, verbose_name='觸發條件')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='比例(%)')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='系統計算＝有效合約額×比例，唯讀', max_digits=14, verbose_name='金額')),
                ('trigger_type', models.CharField(choices=[('manual', '手動'), ('all_signed', '該期全部簽收'), ('weight_threshold', '累計重量達門檻'), ('per_batch', '每批按量分批請')], default='manual', max_length=20, verbose_name='觸發方式')),
                ('threshold_pct', models.DecimalField(blank=True, decimal_places=2, help_text='觸發方式為「累計重量達門檻」時必填。如 80 表示該期累計簽收噸數達 80%', max_digits=5, null=True, verbose_name='門檻(%)')),
                ('weight_basis_kg', models.DecimalField(blank=True, decimal_places=2, help_text='首次觸發時把該期所有批次的總重量固化。之後新增批次不影響已算過的比例', max_digits=12, null=True, verbose_name='鎖定分母(kg)')),
                ('weight_basis_locked_at', models.DateTimeField(blank=True, null=True, verbose_name='分母鎖定時間')),
                ('claimable_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='累計可請金額')),
                ('claimed_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='累計已請金額')),
                ('received_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='累計已收金額')),
                ('state', models.CharField(choices=[('pending', '未到'), ('claimable', '可請款'), ('partial', '部分請款'), ('invoiced', '已請款'), ('received', '已收款')], default='pending', max_length=12, verbose_name='彙總狀態')),
                ('claimable_at', models.DateTimeField(blank=True, help_text='用於「可請款逾 7 天未開單」判定', null=True, verbose_name='首次可請款時間')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='備註')),
            ],
            options={
                'verbose_name': '請款里程碑',
                'verbose_name_plural': '請款里程碑',
                'db_table': 'billing_billingmilestone',
                'ordering': ['project', 'seq'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalBillingClaim',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('seq', models.SmallIntegerField(verbose_name='序號')),
                ('amount', models.DecimalField(decimal_places=2, help_text='單位：元。分批請款時＝里程碑金額×(該批噸數÷該期總噸數)', max_digits=14, verbose_name='金額')),
                ('source', models.CharField(choices=[('auto_signoff', '簽收自動產生'), ('manual', '人工建立')], max_length=20, verbose_name='來源')),
                ('state', models.CharField(choices=[('claimable', '可請款'), ('invoiced', '已請款'), ('received', '已收款')], default='claimable', max_length=12, verbose_name='狀態')),
                ('claimable_at', models.DateTimeField(blank=True, editable=False, verbose_name='可請款時間')),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='請款日')),
                ('invoice_no', models.CharField(blank=True, max_length=30, verbose_name='請款單號')),
                ('receive_date', models.DateField(blank=True, null=True, verbose_name='收款日')),
                ('weight_kg_snapshot', models.DecimalField(blank=True, decimal_places=2, help_text='產生當時該批的重量，供日後對帳', max_digits=12, null=True, verbose_name='噸數快照')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='備註')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical 請款事件',
                'verbose_name_plural': 'historical 請款事件',
                'db_table': 'billing_billingclaim_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalBillingMilestone',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('seq', models.SmallIntegerField(verbose_name='順序')),
                ('label', models.CharField(help_text='如「第一期請款」', max_length=100, verbose_name='名稱')),
                ('trigger_desc', models.CharField(blank=True, help_text='合約原文，如「第一期構件全數運抵工地並經業主簽收」', max_length=200, verbose_name='觸發條件')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='比例(%)')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='系統計算＝有效合約額×比例，唯讀', max_digits=14, verbose_name='金額')),
                ('trigger_type', models.CharField(choices=[('manual', '手動'), ('all_signed', '該期全部簽收'), ('weight_threshold', '累計重量達門檻'), ('per_batch', '每批按量分批請')], default='manual', max_length=20, verbose_name='觸發方式')),
                ('threshold_pct', models.DecimalField(blank=True, decimal_places=2, help_text='觸發方式為「累計重量達門檻」時必填。如 80 表示該期累計簽收噸數達 80%', max_digits=5, null=True, verbose_name='門檻(%)')),
                ('weight_basis_kg', models.DecimalField(blank=True, decimal_places=2, help_text='首次觸發時把該期所有批次的總重量固化。之後新增批次不影響已算過的比例', max_digits=12, null=True, verbose_name='鎖定分母(kg)')),
                ('weight_basis_locked_at', models.DateTimeField(blank=True, null=True, verbose_name='分母鎖定時間')),
                ('claimable_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='累計可請金額')),
                ('claimed_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='累計已請金額')),
                ('received_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='累計已收金額')),
                ('state', models.CharField(choices=[('pending', '未到'), ('claimable', '可請款'), ('partial', '部分請款'), ('invoiced', '已請款'), ('received', '已收款')], default='pending', max_length=12, verbose_name='彙總狀態')),
                ('claimable_at', models.DateTimeField(blank=True, help_text='用於「可請款逾 7 天未開單」判定', null=True, verbose_name='首次可請款時間')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='備註')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical 請款里程碑',
                'verbose_name_plural': 'historical 請款里程碑',
                'db_table': 'billing_billingmilestone_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
