# Generated by Django 5.1.5 on 2026-08-13 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='billingmilestone',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project', verbose_name='專案'),
        ),
        migrations.AddField(
            model_name='historicalbillingmilestone',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalbillingmilestone',
            name='project',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.project', verbose_name='專案'),
        ),
        migrations.AddField(
            model_name='milestonelog',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='操作者'),
        ),
        migrations.AddField(
            model_name='milestonelog',
            name='milestone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='billing.billingmilestone', verbose_name='應收款'),
        ),
        migrations.AddIndex(
            model_name='billingmilestone',
            index=models.Index(fields=['project', 'state'], name='billing_bil_project_c3f616_idx'),
        ),
        migrations.AddIndex(
            model_name='billingmilestone',
            index=models.Index(fields=['state', 'expected_date'], name='billing_bil_state_7e9e95_idx'),
        ),
        migrations.AddIndex(
            model_name='billingmilestone',
            index=models.Index(fields=['state', 'due_date'], name='billing_bil_state_dbc91e_idx'),
        ),
        migrations.AddConstraint(
            model_name='billingmilestone',
            constraint=models.UniqueConstraint(fields=('project', 'seq'), name='uniq_milestone_project_seq'),
        ),
        migrations.AddConstraint(
            model_name='billingmilestone',
            constraint=models.CheckConstraint(condition=models.Q(('seq__gte', 1)), name='ck_milestone_seq_positive'),
        ),
        migrations.AddConstraint(
            model_name='billingmilestone',
            constraint=models.CheckConstraint(condition=models.Q(('percentage__gte', 0), ('percentage__lte', 100)), name='ck_milestone_pct_range'),
        ),
    ]
