# Generated by Django 5.1.5 on 2026-08-02 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('inventory', '0001_initial'),
        ('projects', '0001_initial'),
        ('tracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='billingclaim',
            name='triggered_by_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_claims', to='tracking.trackingunit', verbose_name='觸發來源批次'),
        ),
        migrations.AddField(
            model_name='billingclaimlog',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_changes', to=settings.AUTH_USER_MODEL, verbose_name='操作者'),
        ),
        migrations.AddField(
            model_name='billingclaimlog',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='billing.billingclaim', verbose_name='請款事件'),
        ),
        migrations.AddField(
            model_name='billingmilestone',
            name='phase',
            field=models.ForeignKey(blank=True, help_text='決定哪些批次的簽收會觸發它', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestones', to='projects.projectphase', verbose_name='對應期別'),
        ),
        migrations.AddField(
            model_name='billingmilestone',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project', verbose_name='專案'),
        ),
        migrations.AddField(
            model_name='billingmilestone',
            name='target_location',
            field=models.ForeignKey(blank=True, help_text='合約指定的施工案場／業主廠房。簽收地點不符時警告但不阻擋', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_milestones', to='inventory.location', verbose_name='指定交貨地點'),
        ),
        migrations.AddField(
            model_name='billingmilestone',
            name='weight_basis_changed_by_co',
            field=models.ForeignKey(blank=True, help_text='要修改已鎖定的分母，必須綁一張【已核准】的變更追加單', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocked_milestones', to='projects.changeorder', verbose_name='分母變更依據'),
        ),
        migrations.AddField(
            model_name='billingclaim',
            name='milestone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='billing.billingmilestone', verbose_name='請款里程碑'),
        ),
        migrations.AddField(
            model_name='historicalbillingclaim',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalbillingclaim',
            name='milestone',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='billing.billingmilestone', verbose_name='請款里程碑'),
        ),
        migrations.AddField(
            model_name='historicalbillingclaim',
            name='triggered_by_unit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tracking.trackingunit', verbose_name='觸發來源批次'),
        ),
        migrations.AddField(
            model_name='historicalbillingmilestone',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalbillingmilestone',
            name='phase',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='決定哪些批次的簽收會觸發它', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.projectphase', verbose_name='對應期別'),
        ),
        migrations.AddField(
            model_name='historicalbillingmilestone',
            name='project',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.project', verbose_name='專案'),
        ),
        migrations.AddField(
            model_name='historicalbillingmilestone',
            name='target_location',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='合約指定的施工案場／業主廠房。簽收地點不符時警告但不阻擋', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.location', verbose_name='指定交貨地點'),
        ),
        migrations.AddField(
            model_name='historicalbillingmilestone',
            name='weight_basis_changed_by_co',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='要修改已鎖定的分母，必須綁一張【已核准】的變更追加單', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.changeorder', verbose_name='分母變更依據'),
        ),
        migrations.AddIndex(
            model_name='billingclaimlog',
            index=models.Index(fields=['claim', '-changed_at'], name='billing_bil_claim_i_9de629_idx'),
        ),
        migrations.AddIndex(
            model_name='billingmilestone',
            index=models.Index(fields=['project', 'state'], name='billing_bil_project_c3f616_idx'),
        ),
        migrations.AddIndex(
            model_name='billingmilestone',
            index=models.Index(fields=['trigger_type', 'phase'], name='billing_bil_trigger_184f11_idx'),
        ),
        migrations.AddIndex(
            model_name='billingmilestone',
            index=models.Index(fields=['state', 'claimable_at'], name='billing_bil_state_e3a751_idx'),
        ),
        migrations.AddConstraint(
            model_name='billingmilestone',
            constraint=models.UniqueConstraint(fields=('project', 'seq'), name='uniq_milestone_project_seq'),
        ),
        migrations.AddConstraint(
            model_name='billingmilestone',
            constraint=models.CheckConstraint(condition=models.Q(('percentage__gte', 0), ('percentage__lte', 100)), name='ck_milestone_pct_range'),
        ),
        migrations.AddConstraint(
            model_name='billingmilestone',
            constraint=models.CheckConstraint(condition=models.Q(('claimed_amount__lte', models.F('claimable_amount'))), name='ck_milestone_claimed_lte_claimable'),
        ),
        migrations.AddConstraint(
            model_name='billingmilestone',
            constraint=models.CheckConstraint(condition=models.Q(('received_amount__lte', models.F('claimed_amount'))), name='ck_milestone_received_lte_claimed'),
        ),
        migrations.AddConstraint(
            model_name='billingmilestone',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('trigger_type', 'weight_threshold'), _negated=True), ('threshold_pct__isnull', False), _connector='OR'), name='ck_milestone_threshold_required'),
        ),
        migrations.AddIndex(
            model_name='billingclaim',
            index=models.Index(fields=['milestone', 'state'], name='billing_bil_milesto_c89e62_idx'),
        ),
        migrations.AddIndex(
            model_name='billingclaim',
            index=models.Index(fields=['state', 'claimable_at'], name='billing_bil_state_ff07d1_idx'),
        ),
        migrations.AddIndex(
            model_name='billingclaim',
            index=models.Index(fields=['state', 'invoice_date'], name='billing_bil_state_26f6fc_idx'),
        ),
        migrations.AddIndex(
            model_name='billingclaim',
            index=models.Index(fields=['triggered_by_unit'], name='billing_bil_trigger_4840df_idx'),
        ),
        migrations.AddConstraint(
            model_name='billingclaim',
            constraint=models.UniqueConstraint(fields=('milestone', 'seq'), name='uniq_claim_milestone_seq'),
        ),
        migrations.AddConstraint(
            model_name='billingclaim',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ck_claim_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='billingclaim',
            constraint=models.CheckConstraint(condition=models.Q(('receive_date__isnull', True), ('invoice_date__isnull', True), ('receive_date__gte', models.F('invoice_date')), _connector='OR'), name='ck_claim_receive_after_invoice'),
        ),
    ]
