# Generated by Django 5.1.5 on 2026-08-14 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
        ('tracking', '0002_historicalflowunit_flowunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingmilestone',
            name='trigger_unit',
            field=models.ForeignKey(blank=True, help_text='這個流程完成 → 本期自動轉「可請款」並通知（金流軌）。沒填預計請款日時，現金流預估用它的預計完成日', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_milestones', to='tracking.flowunit', verbose_name='觸發流程'),
        ),
        migrations.AddField(
            model_name='historicalbillingmilestone',
            name='trigger_unit',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='這個流程完成 → 本期自動轉「可請款」並通知（金流軌）。沒填預計請款日時，現金流預估用它的預計完成日', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tracking.flowunit', verbose_name='觸發流程'),
        ),
    ]
