# Generated by Django 5.1.5 on 2026-08-18 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_billingmilestone_trigger_unit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='billingmilestone',
            name='accountant',
            field=models.ForeignKey(blank=True, help_text='D45：觸發流程完成轉可請款時通知這個人，並出現在他的「我的任務」待收款清單', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_milestones', to=settings.AUTH_USER_MODEL, verbose_name='負責收款的會計師'),
        ),
        migrations.AddField(
            model_name='historicalbillingmilestone',
            name='accountant',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='D45：觸發流程完成轉可請款時通知這個人，並出現在他的「我的任務」待收款清單', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='負責收款的會計師'),
        ),
    ]
