# Generated by Django 5.1.5 on 2026-08-13 10:46

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSubcontract',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('code', models.CharField(db_index=True, help_text='SC-YYYY-NNN，系統產生', max_length=30, verbose_name='合約編號')),
                ('title', models.CharField(help_text='如「B區土建工程」「第一期鋼材採購」', max_length=200, verbose_name='合約名稱')),
                ('category', models.CharField(choices=[('subcontract', '分包工程'), ('material', '材料採購'), ('outsource', '外包加工'), ('transport', '運輸')], max_length=20, verbose_name='類別')),
                ('contract_amount', models.DecimalField(decimal_places=2, help_text='單位：元，**未稅**。含稅金額由現金流計算時再加（決策 D31／B2）', max_digits=14, verbose_name='合約金額')),
                ('payment_term_type', models.CharField(choices=[('month_end', '月結'), ('from_invoice', '請款日起算'), ('from_acceptance', '驗收後起算')], default='month_end', max_length=20, verbose_name='付款條件')),
                ('payment_term_days', models.SmallIntegerField(default=30, help_text='常見 30／60／90', verbose_name='帳期天數')),
                ('retention_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='每期扣的百分比，驗收合格後退還。不算的話每期實付金額會高估 5–10%——500 萬的合約就差 25–50 萬', max_digits=5, verbose_name='保留款(%)')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='開始日')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='預計完成')),
                ('status', models.CharField(choices=[('active', '進行中'), ('completed', '已完工'), ('closed', '已結案')], default='active', max_length=12, verbose_name='狀態')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='備註')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, db_constraint=False, help_text='一定要有——這是算得出專案成本與損益的關鍵', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.project', verbose_name='專案')),
                ('vendor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.vendor', verbose_name='廠商')),
            ],
            options={
                'verbose_name': 'historical 分包合約',
                'verbose_name_plural': 'historical 分包合約',
                'db_table': 'payables_subcontract_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Subcontract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('code', models.CharField(help_text='SC-YYYY-NNN，系統產生', max_length=30, unique=True, verbose_name='合約編號')),
                ('title', models.CharField(help_text='如「B區土建工程」「第一期鋼材採購」', max_length=200, verbose_name='合約名稱')),
                ('category', models.CharField(choices=[('subcontract', '分包工程'), ('material', '材料採購'), ('outsource', '外包加工'), ('transport', '運輸')], max_length=20, verbose_name='類別')),
                ('contract_amount', models.DecimalField(decimal_places=2, help_text='單位：元，**未稅**。含稅金額由現金流計算時再加（決策 D31／B2）', max_digits=14, verbose_name='合約金額')),
                ('payment_term_type', models.CharField(choices=[('month_end', '月結'), ('from_invoice', '請款日起算'), ('from_acceptance', '驗收後起算')], default='month_end', max_length=20, verbose_name='付款條件')),
                ('payment_term_days', models.SmallIntegerField(default=30, help_text='常見 30／60／90', verbose_name='帳期天數')),
                ('retention_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='每期扣的百分比，驗收合格後退還。不算的話每期實付金額會高估 5–10%——500 萬的合約就差 25–50 萬', max_digits=5, verbose_name='保留款(%)')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='開始日')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='預計完成')),
                ('status', models.CharField(choices=[('active', '進行中'), ('completed', '已完工'), ('closed', '已結案')], default='active', max_length=12, verbose_name='狀態')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='備註')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subcontracts', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('project', models.ForeignKey(help_text='一定要有——這是算得出專案成本與損益的關鍵', on_delete=django.db.models.deletion.PROTECT, related_name='subcontracts', to='projects.project', verbose_name='專案')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcontracts', to='masters.vendor', verbose_name='廠商')),
            ],
            options={
                'verbose_name': '分包合約',
                'verbose_name_plural': '分包合約',
                'db_table': 'payables_subcontract',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('category', models.CharField(choices=[('subcontract', '分包工程'), ('material', '材料採購'), ('outsource', '外包加工'), ('transport', '運輸')], max_length=20, verbose_name='類別')),
                ('title', models.CharField(help_text='如「第三期計價」「2月份鋼材」', max_length=200, verbose_name='項目')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='未稅金額')),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, help_text='留空＝系統依 5% 自動算。免稅、零稅率請明確填 0——「沒填」與「填 0」是兩件事，不能用同一個值表示', max_digits=14, null=True, verbose_name='稅額')),
                ('retention_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='依合約的保留款比例自動帶入，可覆寫', max_digits=14, verbose_name='本次保留款')),
                ('payable_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='未稅 ＋ 稅額 − 保留款。這才是實際會匯出去的數字，由系統計算', max_digits=14, verbose_name='實付金額')),
                ('state', models.CharField(choices=[('pending', '待計價'), ('approved', '已核可'), ('paid', '已付款')], default='pending', max_length=12, verbose_name='狀態')),
                ('billing_date', models.DateField(blank=True, help_text='包商送單／驗收的日期，付款日由此起算', null=True, verbose_name='計價日')),
                ('due_date', models.DateField(blank=True, help_text='由付款條件推算，可覆寫', null=True, verbose_name='預計付款日')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='核可時間')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='實際付款日')),
                ('payment_method', models.CharField(choices=[('transfer', '匯款'), ('check', '支票'), ('cash', '現金')], default='transfer', max_length=12, verbose_name='付款方式')),
                ('check_due_date', models.DateField(blank=True, help_text='⚠️ 開票日不等於兌現日。填了這欄，現金流就用它算——不填的話，錢會被算成提早兩三個月流出（決策 D31／B1）', null=True, verbose_name='支票到期日')),
                ('check_no', models.CharField(blank=True, max_length=30, verbose_name='票號')),
                ('invoice_no', models.CharField(blank=True, max_length=30, verbose_name='發票號碼')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='備註')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payables', to=settings.AUTH_USER_MODEL, verbose_name='核可者')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payables', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payables', to='projects.project', verbose_name='專案')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payables', to='masters.vendor', verbose_name='廠商')),
                ('subcontract', models.ForeignKey(blank=True, help_text='可空——零星運費、小額採購不必先開合約', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payables', to='payables.subcontract', verbose_name='分包合約')),
            ],
            options={
                'verbose_name': '應付款項',
                'verbose_name_plural': '應付款項',
                'db_table': 'payables_payable',
                'ordering': ['due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPayable',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('category', models.CharField(choices=[('subcontract', '分包工程'), ('material', '材料採購'), ('outsource', '外包加工'), ('transport', '運輸')], max_length=20, verbose_name='類別')),
                ('title', models.CharField(help_text='如「第三期計價」「2月份鋼材」', max_length=200, verbose_name='項目')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='未稅金額')),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, help_text='留空＝系統依 5% 自動算。免稅、零稅率請明確填 0——「沒填」與「填 0」是兩件事，不能用同一個值表示', max_digits=14, null=True, verbose_name='稅額')),
                ('retention_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='依合約的保留款比例自動帶入，可覆寫', max_digits=14, verbose_name='本次保留款')),
                ('payable_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='未稅 ＋ 稅額 − 保留款。這才是實際會匯出去的數字，由系統計算', max_digits=14, verbose_name='實付金額')),
                ('state', models.CharField(choices=[('pending', '待計價'), ('approved', '已核可'), ('paid', '已付款')], default='pending', max_length=12, verbose_name='狀態')),
                ('billing_date', models.DateField(blank=True, help_text='包商送單／驗收的日期，付款日由此起算', null=True, verbose_name='計價日')),
                ('due_date', models.DateField(blank=True, help_text='由付款條件推算，可覆寫', null=True, verbose_name='預計付款日')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='核可時間')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='實際付款日')),
                ('payment_method', models.CharField(choices=[('transfer', '匯款'), ('check', '支票'), ('cash', '現金')], default='transfer', max_length=12, verbose_name='付款方式')),
                ('check_due_date', models.DateField(blank=True, help_text='⚠️ 開票日不等於兌現日。填了這欄，現金流就用它算——不填的話，錢會被算成提早兩三個月流出（決策 D31／B1）', null=True, verbose_name='支票到期日')),
                ('check_no', models.CharField(blank=True, max_length=30, verbose_name='票號')),
                ('invoice_no', models.CharField(blank=True, max_length=30, verbose_name='發票號碼')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='備註')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('approved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='核可者')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.project', verbose_name='專案')),
                ('vendor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.vendor', verbose_name='廠商')),
                ('subcontract', models.ForeignKey(blank=True, db_constraint=False, help_text='可空——零星運費、小額採購不必先開合約', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='payables.subcontract', verbose_name='分包合約')),
            ],
            options={
                'verbose_name': 'historical 應付款項',
                'verbose_name_plural': 'historical 應付款項',
                'db_table': 'payables_payable_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PayableLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_state', models.CharField(blank=True, max_length=12, verbose_name='原狀態')),
                ('to_state', models.CharField(max_length=12, verbose_name='新狀態')),
                ('reason', models.CharField(blank=True, help_text='往回轉時必填', max_length=500, verbose_name='原因')),
                ('amount_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='金額快照')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='異動時間')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payable_changes', to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
                ('payable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='payables.payable', verbose_name='應付款項')),
            ],
            options={
                'verbose_name': '應付狀態歷程',
                'verbose_name_plural': '應付狀態歷程',
                'db_table': 'payables_payablelog',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['payable', '-changed_at'], name='payables_pa_payable_1a4e3d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='subcontract',
            index=models.Index(fields=['project', 'status'], name='payables_su_project_bb3398_idx'),
        ),
        migrations.AddIndex(
            model_name='subcontract',
            index=models.Index(fields=['vendor'], name='payables_su_vendor__ea696a_idx'),
        ),
        migrations.AddConstraint(
            model_name='subcontract',
            constraint=models.CheckConstraint(condition=models.Q(('contract_amount__gte', 0)), name='ck_subcontract_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='subcontract',
            constraint=models.CheckConstraint(condition=models.Q(('retention_pct__gte', 0), ('retention_pct__lte', 100)), name='ck_subcontract_retention_range'),
        ),
        migrations.AddConstraint(
            model_name='subcontract',
            constraint=models.CheckConstraint(condition=models.Q(('payment_term_days__gte', 0), ('payment_term_days__lte', 365)), name='ck_subcontract_term_days_range'),
        ),
        migrations.AddIndex(
            model_name='payable',
            index=models.Index(fields=['project', 'state'], name='payables_pa_project_b00ceb_idx'),
        ),
        migrations.AddIndex(
            model_name='payable',
            index=models.Index(fields=['state', 'due_date'], name='payables_pa_state_c967ed_idx'),
        ),
        migrations.AddIndex(
            model_name='payable',
            index=models.Index(fields=['vendor', 'state'], name='payables_pa_vendor__d48440_idx'),
        ),
        migrations.AddIndex(
            model_name='payable',
            index=models.Index(fields=['subcontract'], name='payables_pa_subcont_c7afe2_idx'),
        ),
        migrations.AddIndex(
            model_name='payable',
            index=models.Index(fields=['check_due_date'], name='payables_pa_check_d_816dbd_idx'),
        ),
        migrations.AddConstraint(
            model_name='payable',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ck_payable_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='payable',
            constraint=models.CheckConstraint(condition=models.Q(('retention_amount__gte', 0)), name='ck_payable_retention_positive'),
        ),
        migrations.AddConstraint(
            model_name='payable',
            constraint=models.CheckConstraint(condition=models.Q(('paid_date__isnull', True), ('billing_date__isnull', True), ('paid_date__gte', models.F('billing_date')), _connector='OR'), name='ck_payable_paid_after_billing'),
        ),
    ]
