# Generated by Django 5.1.5 on 2026-08-14 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payables', '0001_initial'),
        ('tracking', '0002_historicalflowunit_flowunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpayable',
            name='flow_unit',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='這筆錢是為了哪件事花的——訂料款掛「訂料與採購」、表處委外款掛「表面處理」。追蹤單元的花錢內容由此對回來', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tracking.flowunit', verbose_name='所屬流程'),
        ),
        migrations.AddField(
            model_name='payable',
            name='flow_unit',
            field=models.ForeignKey(blank=True, help_text='這筆錢是為了哪件事花的——訂料款掛「訂料與採購」、表處委外款掛「表面處理」。追蹤單元的花錢內容由此對回來', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payables', to='tracking.flowunit', verbose_name='所屬流程'),
        ),
    ]
