# Generated by Django 5.1.5 on 2026-08-29 07:39

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payables', '0002_historicalpayable_flow_unit_payable_flow_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=14, verbose_name='現有現金')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='備註')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '公司現有現金',
                'verbose_name_plural': '公司現有現金',
                'db_table': 'payables_cashbalance',
            },
        ),
    ]
