# Generated by Django 5.1.5 on 2026-08-30 11:10

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_materialitem_worktype'),
        ('payables', '0003_cashbalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayableLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='數量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='單價')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='數量 × 單價，由系統計算', max_digits=14, verbose_name='金額')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payable_lines', to='masters.materialitem', verbose_name='品項')),
                ('payable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payables.payable', verbose_name='應付款項')),
            ],
            options={
                'verbose_name': '應付明細',
                'verbose_name_plural': '應付明細',
                'db_table': 'payables_payableline',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['item'], name='payables_pa_item_id_e3215e_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('qty__gt', 0)), name='ck_payline_qty_positive'), models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='ck_payline_price_positive')],
            },
        ),
    ]
