# Generated by Django 5.1.5 on 2026-08-13 10:46

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import main.apps.core.models.attachment
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.BigIntegerField(verbose_name='關聯物件 ID')),
                ('file', models.FileField(max_length=300, upload_to=main.apps.core.models.attachment.attachment_upload_path, verbose_name='檔案')),
                ('original_name', models.CharField(max_length=255, verbose_name='原始檔名')),
                ('size_bytes', models.BigIntegerField(verbose_name='檔案大小')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME 類型')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='備註')),
                ('category', models.CharField(choices=[('contract', '合約'), ('drawing', '圖說'), ('schedule', '時程表'), ('photo', '現場照片'), ('inspection', '檢驗報告'), ('signoff', '簽收單'), ('invoice', '發票／請款單'), ('other', '其他')], default='other', help_text='一個案子底下可能有二十個檔案。沒有分類就是一坨清單，「合約在哪」會變成一次搜尋而不是一次點擊', max_length=20, verbose_name='分類')),
                ('is_previewable', models.BooleanField(default=False, help_text='上傳時依**實際** MIME 判定，前端不必再從副檔名猜', verbose_name='可預覽')),
                ('checksum', models.CharField(blank=True, db_index=True, help_text='同一份合約被傳兩次時看得出來；日後也可用於完整性驗證', max_length=64, verbose_name='SHA-256')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上傳時間')),
            ],
            options={
                'verbose_name': '附件',
                'verbose_name_plural': '附件',
                'db_table': 'core_attachment',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='部門代號')),
                ('name', models.CharField(max_length=50, verbose_name='部門名稱')),
                ('sort_order', models.SmallIntegerField(default=0, verbose_name='顯示順序')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用中')),
            ],
            options={
                'verbose_name': '部門',
                'verbose_name_plural': '部門',
                'db_table': 'core_department',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='標題')),
                ('body', models.TextField(blank=True, verbose_name='內容')),
                ('link_url', models.CharField(blank=True, max_length=500, verbose_name='跳轉路徑')),
                ('category', models.CharField(choices=[('billing', '請款'), ('tracking', '進度'), ('alert', '警示'), ('system', '系統')], default='system', max_length=20, verbose_name='類別')),
                ('is_read', models.BooleanField(default=False, verbose_name='已讀')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='讀取時間')),
                ('dedup_key', models.CharField(blank=True, db_index=True, help_text='防止同一件事天天轟炸。格式如 alert:stalled:unit_130', max_length=150, verbose_name='去重鍵')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'db_table': 'core_notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='參數代號')),
                ('name', models.CharField(max_length=100, verbose_name='名稱')),
                ('value', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='數值')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='單位')),
                ('effective_from', models.DateField(verbose_name='生效日')),
                ('effective_to', models.DateField(blank=True, help_text='留空表示仍有效', null=True, verbose_name='失效日')),
                ('source_note', models.TextField(blank=True, verbose_name='依據說明')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '系統參數',
                'verbose_name_plural': '系統參數',
                'db_table': 'core_systemparameter',
                'ordering': ['code', '-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('employee_no', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='員工編號')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='職稱')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='手機')),
                ('must_change_password', models.BooleanField(default=True, verbose_name='需修改密碼')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '使用者',
                'verbose_name_plural': '使用者',
                'db_table': 'core_user',
                'ordering': ['employee_no', 'username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(help_text='人類可讀的一句話，如「固越案·第一期-1F鋼柱 進入 進場簽收」', max_length=300, verbose_name='描述')),
                ('category', models.CharField(choices=[('project', '專案'), ('tracking', '進度'), ('billing', '請款'), ('system', '系統')], max_length=20, verbose_name='類別')),
                ('object_id', models.BigIntegerField(blank=True, null=True, verbose_name='關聯物件 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='時間')),
                ('actor', models.ForeignKey(blank=True, help_text='系統自動產生時為空', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='關聯類型')),
            ],
            options={
                'verbose_name': '動態',
                'verbose_name_plural': '動態',
                'db_table': 'core_activitylog',
                'ordering': ['-created_at'],
            },
        ),
    ]
