# Generated by Django 5.1.5 on 2026-08-02 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.BigIntegerField(verbose_name='關聯物件 ID')),
                ('file', models.FileField(max_length=300, upload_to='attachments/%Y/%m/', verbose_name='檔案')),
                ('original_name', models.CharField(max_length=255, verbose_name='原始檔名')),
                ('size_bytes', models.BigIntegerField(verbose_name='檔案大小')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME 類型')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='備註')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上傳時間')),
            ],
            options={
                'verbose_name': '附件',
                'verbose_name_plural': '附件',
                'db_table': 'core_attachment',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='標題')),
                ('body', models.TextField(blank=True, verbose_name='內容')),
                ('link_url', models.CharField(blank=True, max_length=500, verbose_name='跳轉路徑')),
                ('category', models.CharField(choices=[('billing', '請款'), ('tracking', '進度'), ('alert', '警示'), ('asset', '資產'), ('system', '系統')], default='system', max_length=20, verbose_name='類別')),
                ('is_read', models.BooleanField(default=False, verbose_name='已讀')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='讀取時間')),
                ('dedup_key', models.CharField(blank=True, db_index=True, help_text='防止同一件事天天轟炸。格式如 alert:awaiting_signoff:unit_130', max_length=150, verbose_name='去重鍵')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'db_table': 'core_notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='參數代號')),
                ('name', models.CharField(max_length=100, verbose_name='名稱')),
                ('value', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='數值')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='單位')),
                ('effective_from', models.DateField(verbose_name='生效日')),
                ('effective_to', models.DateField(blank=True, help_text='留空表示仍有效', null=True, verbose_name='失效日')),
                ('source_note', models.TextField(blank=True, verbose_name='依據說明')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '系統參數',
                'verbose_name_plural': '系統參數',
                'db_table': 'core_systemparameter',
                'ordering': ['code', '-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(help_text='人類可讀的一句話，如「固越案·第一期-1F鋼柱 進入 進場簽收」', max_length=300, verbose_name='描述')),
                ('category', models.CharField(choices=[('project', '專案'), ('tracking', '進度'), ('billing', '請款'), ('line', '產線'), ('asset', '資產'), ('system', '系統')], max_length=20, verbose_name='類別')),
                ('object_id', models.BigIntegerField(blank=True, null=True, verbose_name='關聯物件 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='時間')),
                ('actor', models.ForeignKey(blank=True, help_text='系統自動產生時為空', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='關聯類型')),
            ],
            options={
                'verbose_name': '動態',
                'verbose_name_plural': '動態',
                'db_table': 'core_activitylog',
                'ordering': ['-created_at'],
            },
        ),
    ]
