# Generated by Django 5.1.5 on 2026-08-02 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0002_attachment_notification_systemparameter_activitylog'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='project',
            field=models.ForeignKey(blank=True, help_text='用於資料可見範圍過濾', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='projects.project', verbose_name='所屬專案'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='關聯類型'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL, verbose_name='上傳者'),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='收件者'),
        ),
        migrations.AddField(
            model_name='systemparameter',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='更新者'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['project', '-created_at'], name='core_activi_project_a13552_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['content_type', 'object_id'], name='core_attach_content_d3cac2_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read', '-created_at'], name='core_notifi_recipie_1d5476_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['dedup_key', 'created_at'], name='core_notifi_dedup_k_691343_idx'),
        ),
        migrations.AddConstraint(
            model_name='systemparameter',
            constraint=models.UniqueConstraint(fields=('code', 'effective_from'), name='uniq_param_code_from'),
        ),
        migrations.AddConstraint(
            model_name='systemparameter',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gt', models.F('effective_from')), _connector='OR'), name='ck_param_period_valid'),
        ),
    ]
