# Generated by Django 5.1.5 on 2026-09-01 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('billing', '請款'), ('tracking', '進度'), ('alert', '警示'), ('affair', '行政'), ('system', '系統')], default='system', max_length=20, verbose_name='類別'),
        ),
    ]
