# Generated by Django 5.1.5 on 2026-08-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KpiSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpi_code', models.CharField(help_text='如 oee、inventory_turnover', max_length=40, verbose_name='KPI 代號')),
                ('period_type', models.CharField(help_text='daily／monthly／yearly／rolling12m', max_length=10, verbose_name='週期類型')),
                ('period_start', models.DateField(verbose_name='統計起日')),
                ('period_end', models.DateField(verbose_name='統計迄日')),
                ('scope_type', models.CharField(help_text='company／project／equipment／department／vendor', max_length=20, verbose_name='範圍類型')),
                ('scope_id', models.BigIntegerField(blank=True, help_text='company 時為空', null=True, verbose_name='範圍 ID')),
                ('value', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='KPI 值')),
                ('numerator', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='分子')),
                ('denominator', models.DecimalField(blank=True, decimal_places=6, help_text='為 0 時狀態應為「無資料」而非「未達標」', max_digits=18, null=True, verbose_name='分母')),
                ('target_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='目標值')),
                ('warning_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='警示門檻')),
                ('status', models.CharField(choices=[('good', '達標'), ('warn', '注意'), ('bad', '未達標'), ('nodata', '無資料')], max_length=10, verbose_name='狀態')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='備註')),
                ('computed_at', models.DateTimeField(auto_now_add=True, verbose_name='計算時間')),
            ],
            options={
                'verbose_name': 'KPI 快照',
                'verbose_name_plural': 'KPI 快照',
                'db_table': 'analytics_kpisnapshot',
                'ordering': ['kpi_code', '-period_start'],
                'indexes': [models.Index(fields=['kpi_code', 'scope_type', 'scope_id', '-period_start'], name='analytics_k_kpi_cod_6d7350_idx')],
                'constraints': [models.UniqueConstraint(fields=('kpi_code', 'period_type', 'period_start', 'scope_type', 'scope_id'), name='uniq_kpi_snapshot')],
            },
        ),
    ]
