# Generated by Django 5.1.5 on 2026-08-02 06:13

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProject',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('code', models.CharField(db_index=True, help_text='P-YYYY-NNN，系統產生', max_length=20, verbose_name='專案編號')),
                ('name', models.CharField(max_length=200, verbose_name='案名')),
                ('project_type', models.CharField(choices=[('civil', '土建'), ('steel', '鋼構'), ('mixed', '混合')], max_length=10, verbose_name='專案類型')),
                ('contract_amount', models.DecimalField(blank=True, decimal_places=2, help_text='單位：新台幣元。投標中未定可留空', max_digits=14, null=True, verbose_name='合約總額')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='開工日')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='預計完工')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='實際完工')),
                ('status', models.CharField(choices=[('ontrack', '正常'), ('atrisk', '注意'), ('delayed', '延誤')], default='ontrack', max_length=10, verbose_name='狀態')),
                ('is_closed', models.BooleanField(default=False, verbose_name='已結案')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='備註')),
                ('contract_terms', models.TextField(blank=True, help_text='工期、請款條件、罰則、保固', verbose_name='合約條款')),
                ('quote_info', models.TextField(blank=True, verbose_name='報價資訊')),
                ('doc_links', models.TextField(blank=True, help_text='圖紙雲端連結、聯絡窗口等', verbose_name='文件連結')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.customer', verbose_name='客戶')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('main_stage', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.stage', verbose_name='目前主線階段')),
                ('main_template', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.stagetemplate', verbose_name='主線模板')),
                ('owner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='專案負責人')),
            ],
            options={
                'verbose_name': 'historical 專案',
                'verbose_name_plural': 'historical 專案',
                'db_table': 'projects_project_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('code', models.CharField(help_text='P-YYYY-NNN，系統產生', max_length=20, unique=True, verbose_name='專案編號')),
                ('name', models.CharField(max_length=200, verbose_name='案名')),
                ('project_type', models.CharField(choices=[('civil', '土建'), ('steel', '鋼構'), ('mixed', '混合')], max_length=10, verbose_name='專案類型')),
                ('contract_amount', models.DecimalField(blank=True, decimal_places=2, help_text='單位：新台幣元。投標中未定可留空', max_digits=14, null=True, verbose_name='合約總額')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='開工日')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='預計完工')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='實際完工')),
                ('status', models.CharField(choices=[('ontrack', '正常'), ('atrisk', '注意'), ('delayed', '延誤')], default='ontrack', max_length=10, verbose_name='狀態')),
                ('is_closed', models.BooleanField(default=False, verbose_name='已結案')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='備註')),
                ('contract_terms', models.TextField(blank=True, help_text='工期、請款條件、罰則、保固', verbose_name='合約條款')),
                ('quote_info', models.TextField(blank=True, verbose_name='報價資訊')),
                ('doc_links', models.TextField(blank=True, help_text='圖紙雲端連結、聯絡窗口等', verbose_name='文件連結')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='masters.customer', verbose_name='客戶')),
                ('main_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_projects', to='masters.stage', verbose_name='目前主線階段')),
                ('main_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='main_projects', to='masters.stagetemplate', verbose_name='主線模板')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_projects', to=settings.AUTH_USER_MODEL, verbose_name='專案負責人')),
            ],
            options={
                'verbose_name': '專案',
                'verbose_name_plural': '專案',
                'db_table': 'projects_project',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalChangeOrder',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='CO-YYYY-NNN', max_length=30, verbose_name='變更單號')),
                ('title', models.CharField(max_length=200, verbose_name='標題')),
                ('amount', models.DecimalField(decimal_places=2, help_text='單位：元。追加為正、減帳為負', max_digits=14, verbose_name='變更金額')),
                ('reason', models.TextField(verbose_name='變更原因')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已送簽'), ('approved', '已核准'), ('rejected', '已駁回')], default='draft', max_length=10, verbose_name='狀態')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='核准時間')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('approved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='核准者')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.project', verbose_name='專案')),
            ],
            options={
                'verbose_name': 'historical 變更追加單',
                'verbose_name_plural': 'historical 變更追加單',
                'db_table': 'projects_changeorder_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ChangeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='CO-YYYY-NNN', max_length=30, unique=True, verbose_name='變更單號')),
                ('title', models.CharField(max_length=200, verbose_name='標題')),
                ('amount', models.DecimalField(decimal_places=2, help_text='單位：元。追加為正、減帳為負', max_digits=14, verbose_name='變更金額')),
                ('reason', models.TextField(verbose_name='變更原因')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已送簽'), ('approved', '已核准'), ('rejected', '已駁回')], default='draft', max_length=10, verbose_name='狀態')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='核准時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_change_orders', to=settings.AUTH_USER_MODEL, verbose_name='核准者')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_change_orders', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_orders', to='projects.project', verbose_name='專案')),
            ],
            options={
                'verbose_name': '變更追加單',
                'verbose_name_plural': '變更追加單',
                'db_table': 'projects_changeorder',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.SmallIntegerField(verbose_name='順序')),
                ('name', models.CharField(help_text='如「第一期」', max_length=50, verbose_name='期別名稱')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='備註')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='projects.project', verbose_name='專案')),
            ],
            options={
                'verbose_name': '期別',
                'verbose_name_plural': '期別',
                'db_table': 'projects_projectphase',
                'ordering': ['project', 'seq'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='projects_pr_status_f023cb_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_closed', 'due_date'], name='projects_pr_is_clos_3c3053_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['owner'], name='projects_pr_owner_i_dea3a1_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_type'], name='projects_pr_project_573ce6_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['customer'], name='projects_pr_custome_787ddb_idx'),
        ),
        migrations.AddIndex(
            model_name='changeorder',
            index=models.Index(fields=['project', 'status'], name='projects_ch_project_5dfe49_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectphase',
            constraint=models.UniqueConstraint(fields=('project', 'seq'), name='uniq_phase_project_seq'),
        ),
    ]
