# Generated by Django 5.1.5 on 2026-08-14 12:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_flowstage_flowitem'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='estimate_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='未簽約時金流預測與期別金額用它當基準；簽約後以合約額為準', max_digits=14, null=True, verbose_name='估價金額'),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='lifecycle',
            field=models.CharField(choices=[('active', '進行中'), ('lost', '未成交'), ('paused', '暫停'), ('closed', '已結案')], default='active', help_text='進行中／未成交／暫停／已結案。從詢價就建案（2026-08-14 確認）', max_length=10, verbose_name='生命週期'),
        ),
        migrations.AddField(
            model_name='project',
            name='estimate_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='未簽約時金流預測與期別金額用它當基準；簽約後以合約額為準', max_digits=14, null=True, verbose_name='估價金額'),
        ),
        migrations.AddField(
            model_name='project',
            name='lifecycle',
            field=models.CharField(choices=[('active', '進行中'), ('lost', '未成交'), ('paused', '暫停'), ('closed', '已結案')], default='active', help_text='進行中／未成交／暫停／已結案。從詢價就建案（2026-08-14 確認）', max_length=10, verbose_name='生命週期'),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='contract_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='單位：新台幣元。簽約前留空', max_digits=14, null=True, verbose_name='合約總額'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contract_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='單位：新台幣元。簽約前留空', max_digits=14, null=True, verbose_name='合約總額'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['lifecycle'], name='projects_pr_lifecyc_f8886f_idx'),
        ),
    ]
